import type { BusinessCapability } from "../types";

export const WAREHOUSE_CAPABILITY: BusinessCapability = {
  id: "cap_warehouse",
  name: "Warehouse Management",
  description: "Mengelola operasional gudang termasuk penataan, picking, packing, dan pengiriman",
  domain: "warehouse",
  version: "1.0.0",
  ownerExecutive: "COO",
  supportedActions: [
    {
      name: "Create Warehouse",
      purpose: "Mendaftarkan gudang atau lokasi penyimpanan baru",
      whenUsed: "Ekspansi cabang, kebutuhan gudang baru, atau pemisahan kategori stok",
      requiredContext: ["name", "location", "capacity", "branchId", "type"],
      approvalLevel: "manager",
      riskLevel: "low",
      eventsGenerated: ["warehouse.created", "warehouse.configured"],
      executionHandler: "WarehouseCreateHandler",
      kpisAffected: ["warehouse_utilization", "storage_capacity"],
      businessConstraints: ["Setiap cabang minimal 1 gudang aktif"],
      rollbackStrategy: "Deactivate warehouse and reassign inventory",
      examples: ["Buat gudang baru untuk Branch 5", "Tambah cold storage untuk produk frozen"],
    },
    {
      name: "Arrange Layout",
      purpose: "Mengatur tata letak dan zonasi gudang untuk efisiensi penyimpanan",
      whenUsed: "Gudang baru, perubahan kategori produk, atau optimasi ruang",
      requiredContext: ["warehouseId", "zoneConfig", "layoutType"],
      approvalLevel: "manager",
      riskLevel: "low",
      eventsGenerated: ["warehouse.layout.updated", "warehouse.zone.changed"],
      executionHandler: "WarehouseArrangeLayoutHandler",
      kpisAffected: ["warehouse_efficiency", "picking_accuracy"],
      businessConstraints: ["Zonasi harus sesuai kategori produk (dry, frozen, hazardous)"],
      rollbackStrategy: "Restore previous layout configuration",
      examples: ["Atur ulang zonasi gudang pusat", "Konfigurasi rak berdasarkan fast-moving items"],
    },
    {
      name: "Pick Items",
      purpose: "Mengambil barang dari rak untuk memenuhi pesanan atau produksi",
      whenUsed: "Ada pesanan pelanggan, transfer stok, atau kebutuhan produksi",
      requiredContext: ["orderId", "items", "warehouseId", "pickerId"],
      approvalLevel: "none",
      riskLevel: "low",
      eventsGenerated: ["warehouse.picking.started", "warehouse.picking.completed"],
      executionHandler: "WarehousePickHandler",
      kpisAffected: ["picking_accuracy", "picking_efficiency", "order_fulfillment_time"],
      businessConstraints: ["FIFO untuk produk perishable", "Picking ganda harus dihindari"],
      rollbackStrategy: "Return picked items to shelves",
      examples: ["Pick 10 item untuk pesanan SO-001", "Picking bahan baku untuk produksi shift 1"],
    },
    {
      name: "Pack Items",
      purpose: "Mengemas barang yang sudah di-pick untuk pengiriman atau penyerahan",
      whenUsed: "Setelah picking selesai, sebelum pengiriman atau penyerahan ke pelanggan",
      requiredContext: ["orderId", "items", "packagingType", "packerId"],
      approvalLevel: "none",
      riskLevel: "low",
      eventsGenerated: ["warehouse.packing.completed", "warehouse.shipment.ready"],
      executionHandler: "WarehousePackHandler",
      kpisAffected: ["packing_efficiency", "packaging_cost"],
      businessConstraints: ["Produk pecah belah wajib bubble wrap", "Berat paket tidak melebihi kapasitas"],
      rollbackStrategy: "Unpack and return to picked state",
      examples: ["Pack 10 item untuk pengiriman ekspedisi", "Kemas kue untuk delivery catering"],
    },
    {
      name: "Ship Items",
      purpose: "Mengirim barang ke pelanggan atau cabang lain",
      whenUsed: "Setelah packing, untuk pengiriman ke pelanggan atau transfer antar cabang",
      requiredContext: ["orderId", "items", "carrier", "destination", "shippingDate"],
      approvalLevel: "none",
      riskLevel: "medium",
      eventsGenerated: ["warehouse.shipped", "warehouse.shipment.sent", "stock.decreased"],
      executionHandler: "WarehouseShipHandler",
      kpisAffected: ["on_time_delivery", "shipping_cost", "delivery_accuracy"],
      businessConstraints: ["Alamat pengiriman harus valid", "Ekspedisi harus sesuai kontrak"],
      rollbackStrategy: "Recall shipment if not yet delivered",
      examples: ["Kirim pesanan SO-001 via JNE", "Transfer stok antar cabang via ekspedisi"],
    },
    {
      name: "Receive Transfer",
      purpose: "Menerima barang transfer dari cabang atau gudang lain",
      whenUsed: "Barang transfer tiba di gudang tujuan",
      requiredContext: ["transferOrderId", "receivedItems", "warehouseId", "receivedById"],
      approvalLevel: "none",
      riskLevel: "low",
      eventsGenerated: ["warehouse.transfer.received", "stock.increased", "transfer.completed"],
      executionHandler: "WarehouseReceiveTransferHandler",
      kpisAffected: ["transfer_accuracy", "receiving_efficiency"],
      businessConstraints: ["Quantity diterima harus sesuai transfer order"],
      rollbackStrategy: "Reverse transfer receipt",
      examples: ["Terima transfer 20 dus dari Gudang A", "Receiving transfer dari Branch 2"],
    },
  ],
  requiredApprovals: ["manager"],
  requiredRoles: ["warehouse_staff", "warehouse_supervisor", "warehouse_manager", "logistics_coordinator"],
  requiredContext: ["branchId", "warehouseId", "userId"],
  requiredCapabilities: ["cap_inventory"],
  generatedEvents: [
    "warehouse.created", "warehouse.layout.updated", "warehouse.picking.completed",
    "warehouse.packing.completed", "warehouse.shipped", "warehouse.transfer.received",
  ],
  affectedKPIs: [
    "warehouse_utilization", "picking_accuracy", "picking_efficiency",
    "on_time_delivery", "shipping_cost",
  ],
  executionHandler: "WarehouseExecutionHandler",
  estimatedRisk: "low",
  estimatedComplexity: "moderate",
  dependencies: ["cap_inventory"],
  postConditions: ["Stok terupdate", "Pesanan terproses", "Riwayat penyimpanan tercatat"],
  rollbackStrategy: "Reverse warehouse transaction and adjust inventory",
  executionType: "immediate",
  status: "active",
  tags: ["warehouse", "logistics", "picking", "packing", "shipping", "fulfillment"],
  examples: ["Operasional gudang harian", "Picking dan packing untuk pesanan", "Pengiriman dan transfer stok"],
};
