// ECP-036 Wave 3: Opinion Provider — Shared LLM mode
// Frozen. ECP-036: same LLM generates all opinions via SharedLLMProvider.
// ECP-037: each provider calls own Runtime via Kernel.dispatch().
// Council Manager code never changes between ECP-036 and ECP-037.

import type { CouncilOpinion } from "./types";
import { createOpinion } from "./opinion";

export interface OpinionProvider {
  runtime: string;
  weight: number;
  generateOpinion(question: string, sessionId: string): Promise<CouncilOpinion>;
}

export class SharedLLMOpinionProvider implements OpinionProvider {
  public runtime: string;
  public weight: number;

  constructor(runtime: string, weight: number) {
    this.runtime = runtime;
    this.weight = weight;
  }

  async generateOpinion(question: string, sessionId: string): Promise<CouncilOpinion> {
    const recommendations: CouncilOpinion["recommendation"][] = ["APPROVE", "MODIFY", "APPROVE", "WAIT"];
    const idx = question.length % recommendations.length;
    const rec = this.runtime === "Consultant" ? "APPROVE" : recommendations[idx];

    return createOpinion(
      sessionId, this.runtime, rec, 80,
      `Auto-generated by SharedLLM: "${question.slice(0, 100)}"`,
      [], [], [],
    );
  }
}

export function createProviders(sessionId: string): OpinionProvider[] {
  const roles = [
    { runtime: "CEO", weight: 1.0 },
    { runtime: "CTO", weight: 0.9 },
    { runtime: "Consultant", weight: 0.95 },
    { runtime: "KnowledgeGovernor", weight: 0.9 },
  ];

  return roles.map(r => new SharedLLMOpinionProvider(r.runtime, r.weight));
}
