import type { KPIDefinition } from "../types";
import type { Dimension } from "../types";

const KPI_DEFINITIONS: KPIDefinition[] = [
  // Sales
  { id: "kpi_revenue", name: "Revenue", description: "Total pendapatan bersih", dimension: "sales", ownerExecutive: "CMO", unit: "IDR", higherIsBetter: true, calculation: "SUM(order_total) - SUM(discount)", dataSource: "orders", refreshInterval: "daily", tags: ["sales", "revenue", "core"] },
  { id: "kpi_gross_sales", name: "Gross Sales", description: "Total penjualan kotor sebelum diskon", dimension: "sales", ownerExecutive: "CMO", unit: "IDR", higherIsBetter: true, calculation: "SUM(order_total)", dataSource: "orders", refreshInterval: "daily", tags: ["sales", "revenue"] },
  { id: "kpi_net_sales", name: "Net Sales", description: "Penjualan bersih setelah retur dan diskon", dimension: "sales", ownerExecutive: "CMO", unit: "IDR", higherIsBetter: true, calculation: "GrossSales - Returns - Discounts", dataSource: "orders", refreshInterval: "daily", tags: ["sales", "revenue"] },
  { id: "kpi_aov", name: "Average Order Value", description: "Rata-rata nilai per order", dimension: "sales", ownerExecutive: "CMO", unit: "IDR", higherIsBetter: true, calculation: "Revenue / OrderCount", dataSource: "orders", refreshInterval: "daily", tags: ["sales", "efficiency"] },
  { id: "kpi_orders", name: "Orders", description: "Jumlah total pesanan", dimension: "sales", ownerExecutive: "CMO", unit: "count", higherIsBetter: true, calculation: "COUNT(orders)", dataSource: "orders", refreshInterval: "daily", tags: ["sales", "volume"] },
  { id: "kpi_order_conversion", name: "Order Conversion Rate", description: "Persentase prospek menjadi order", dimension: "sales", ownerExecutive: "CMO", unit: "%", higherIsBetter: true, calculation: "(Orders / Leads) * 100", dataSource: "crm", refreshInterval: "weekly", tags: ["sales", "conversion"] },
  { id: "kpi_sales_target", name: "Sales Target Achievement", description: "Persentase pencapaian target penjualan", dimension: "sales", ownerExecutive: "CMO", unit: "%", higherIsBetter: true, calculation: "(ActualSales / TargetSales) * 100", dataSource: "sales", refreshInterval: "monthly", tags: ["sales", "target"] },

  // Inventory
  { id: "kpi_inventory_turnover", name: "Inventory Turnover", description: "Perputaran stok dalam periode", dimension: "inventory", ownerExecutive: "COO", unit: "x", higherIsBetter: true, calculation: "COGS / AvgInventory", dataSource: "inventory", refreshInterval: "monthly", tags: ["inventory", "efficiency"] },
  { id: "kpi_inventory_value", name: "Inventory Value", description: "Total nilai stok saat ini", dimension: "inventory", ownerExecutive: "COO", unit: "IDR", higherIsBetter: false, calculation: "SUM(Stock * UnitCost)", dataSource: "inventory", refreshInterval: "daily", tags: ["inventory", "value"] },
  { id: "kpi_stock_accuracy", name: "Stock Accuracy", description: "Akurasi stok fisik vs sistem", dimension: "inventory", ownerExecutive: "COO", unit: "%", higherIsBetter: true, calculation: "(1 - ABS(Physical - System) / System) * 100", dataSource: "stocktake", refreshInterval: "monthly", tags: ["inventory", "quality"] },
  { id: "kpi_waste_pct", name: "Waste Percentage", description: "Persentase produk terbuang", dimension: "inventory", ownerExecutive: "COO", unit: "%", higherIsBetter: false, calculation: "(WasteValue / TotalValue) * 100", dataSource: "inventory", refreshInterval: "weekly", tags: ["inventory", "waste"] },
  { id: "kpi_stockout_rate", name: "Stockout Rate", description: "Frekuensi stok habis", dimension: "inventory", ownerExecutive: "COO", unit: "events/month", higherIsBetter: false, calculation: "COUNT(stockout events)", dataSource: "inventory", refreshInterval: "monthly", tags: ["inventory", "risk"] },
  { id: "kpi_dead_stock", name: "Dead Stock Value", description: "Nilai stok mati (90+ hari tidak bergerak)", dimension: "inventory", ownerExecutive: "COO", unit: "IDR", higherIsBetter: false, calculation: "SUM(DeadStock * UnitCost)", dataSource: "inventory", refreshInterval: "weekly", tags: ["inventory", "slow-moving"] },

  // Finance
  { id: "kpi_gross_margin", name: "Gross Margin", description: "Margin kotor penjualan", dimension: "finance", ownerExecutive: "CFO", unit: "%", higherIsBetter: true, calculation: "((Revenue - COGS) / Revenue) * 100", dataSource: "finance", refreshInterval: "monthly", tags: ["finance", "profitability"] },
  { id: "kpi_net_margin", name: "Net Margin", description: "Margin bersih setelah semua biaya", dimension: "finance", ownerExecutive: "CFO", unit: "%", higherIsBetter: true, calculation: "(NetProfit / Revenue) * 100", dataSource: "finance", refreshInterval: "monthly", tags: ["finance", "profitability"] },
  { id: "kpi_cash_flow", name: "Cash Flow", description: "Arus kas operasional", dimension: "finance", ownerExecutive: "CFO", unit: "IDR", higherIsBetter: true, calculation: "CashIn - CashOut", dataSource: "finance", refreshInterval: "daily", tags: ["finance", "cash", "liquidity"] },
  { id: "kpi_burn_rate", name: "Burn Rate", description: "Kecepatan pengeluaran kas bulanan", dimension: "finance", ownerExecutive: "CFO", unit: "IDR/month", higherIsBetter: false, calculation: "AVG(MonthlyExpenses)", dataSource: "finance", refreshInterval: "monthly", tags: ["finance", "cash", "risk"] },
  { id: "kpi_ebitda", name: "EBITDA", description: "Laba sebelum bunga, pajak, depresiasi, amortisasi", dimension: "finance", ownerExecutive: "CFO", unit: "IDR", higherIsBetter: true, calculation: "NetProfit + Interest + Tax + Depreciation + Amortization", dataSource: "finance", refreshInterval: "monthly", tags: ["finance", "profitability"] },
  { id: "kpi_operating_expense", name: "Operating Expense", description: "Biaya operasional bulanan", dimension: "finance", ownerExecutive: "CFO", unit: "IDR", higherIsBetter: false, calculation: "SUM(OperatingExpenses)", dataSource: "finance", refreshInterval: "monthly", tags: ["finance", "cost"] },
  { id: "kpi_working_capital", name: "Working Capital", description: "Modal kerja bersih", dimension: "finance", ownerExecutive: "CFO", unit: "IDR", higherIsBetter: true, calculation: "CurrentAssets - CurrentLiabilities", dataSource: "finance", refreshInterval: "monthly", tags: ["finance", "liquidity"] },
  { id: "kpi_dso", name: "Days Sales Outstanding", description: "Rata-rata hari penagihan piutang", dimension: "finance", ownerExecutive: "CFO", unit: "days", higherIsBetter: false, calculation: "(Receivables / Revenue) * 30", dataSource: "finance", refreshInterval: "monthly", tags: ["finance", "receivable"] },

  // HR
  { id: "kpi_attendance", name: "Attendance Rate", description: "Tingkat kehadiran karyawan", dimension: "hr", ownerExecutive: "CHRO", unit: "%", higherIsBetter: true, calculation: "(PresentDays / TotalWorkDays) * 100", dataSource: "attendance", refreshInterval: "monthly", tags: ["hr", "attendance"] },
  { id: "kpi_turnover", name: "Employee Turnover", description: "Tingkat pergantian karyawan", dimension: "hr", ownerExecutive: "CHRO", unit: "%", higherIsBetter: false, calculation: "(ResignedCount / AvgHeadcount) * 100", dataSource: "hr", refreshInterval: "monthly", tags: ["hr", "retention"] },
  { id: "kpi_productivity", name: "Productivity Index", description: "Produktivitas per karyawan", dimension: "hr", ownerExecutive: "CHRO", unit: "IDR/employee", higherIsBetter: true, calculation: "Revenue / Headcount", dataSource: "hr", refreshInterval: "monthly", tags: ["hr", "productivity"] },
  { id: "kpi_overtime_pct", name: "Overtime Percentage", description: "Persentase jam lembur", dimension: "hr", ownerExecutive: "CHRO", unit: "%", higherIsBetter: false, calculation: "(OvertimeHours / TotalHours) * 100", dataSource: "attendance", refreshInterval: "weekly", tags: ["hr", "overtime"] },
  { id: "kpi_headcount", name: "Headcount", description: "Jumlah total karyawan", dimension: "hr", ownerExecutive: "CHRO", unit: "count", higherIsBetter: true, calculation: "COUNT(employees)", dataSource: "hr", refreshInterval: "weekly", tags: ["hr", "staffing"] },

  // Marketing
  { id: "kpi_cac", name: "Customer Acquisition Cost", description: "Biaya akuisisi per pelanggan baru", dimension: "marketing", ownerExecutive: "CMO", unit: "IDR", higherIsBetter: false, calculation: "TotalMarketingCost / NewCustomers", dataSource: "marketing", refreshInterval: "monthly", tags: ["marketing", "acquisition"] },
  { id: "kpi_roas", name: "ROAS", description: "Return on Ad Spend", dimension: "marketing", ownerExecutive: "CMO", unit: "x", higherIsBetter: true, calculation: "AdRevenue / AdSpend", dataSource: "marketing", refreshInterval: "weekly", tags: ["marketing", "ads"] },
  { id: "kpi_conversion_rate", name: "Conversion Rate", description: "Tingkat konversi marketing", dimension: "marketing", ownerExecutive: "CMO", unit: "%", higherIsBetter: true, calculation: "(Conversions / Impressions) * 100", dataSource: "marketing", refreshInterval: "weekly", tags: ["marketing", "conversion"] },
  { id: "kpi_engagement", name: "Engagement Rate", description: "Tingkat engagement media sosial", dimension: "marketing", ownerExecutive: "CMO", unit: "%", higherIsBetter: true, calculation: "(Interactions / Reach) * 100", dataSource: "social_media", refreshInterval: "weekly", tags: ["marketing", "social"] },
  { id: "kpi_marketing_roi", name: "Marketing ROI", description: "ROI keseluruhan marketing", dimension: "marketing", ownerExecutive: "CMO", unit: "%", higherIsBetter: true, calculation: "((RevenueFromMarketing - Cost) / Cost) * 100", dataSource: "marketing", refreshInterval: "monthly", tags: ["marketing", "roi"] },
  { id: "kpi_lead_count", name: "Lead Count", description: "Jumlah prospek baru", dimension: "marketing", ownerExecutive: "CMO", unit: "count", higherIsBetter: true, calculation: "COUNT(leads)", dataSource: "crm", refreshInterval: "daily", tags: ["marketing", "leads"] },

  // Production
  { id: "kpi_yield", name: "Production Yield", description: "Persentase produk jadi yang memenuhi standar", dimension: "production", ownerExecutive: "COO", unit: "%", higherIsBetter: true, calculation: "(GoodOutput / TotalOutput) * 100", dataSource: "production", refreshInterval: "daily", tags: ["production", "quality"] },
  { id: "kpi_production_waste", name: "Production Waste", description: "Biaya produksi yang terbuang", dimension: "production", ownerExecutive: "COO", unit: "IDR", higherIsBetter: false, calculation: "SUM(DefectCost + ReworkCost)", dataSource: "production", refreshInterval: "weekly", tags: ["production", "waste"] },
  { id: "kpi_oee", name: "OEE", description: "Overall Equipment Effectiveness", dimension: "production", ownerExecutive: "COO", unit: "%", higherIsBetter: true, calculation: "Availability * Performance * Quality", dataSource: "production", refreshInterval: "daily", tags: ["production", "efficiency"] },
  { id: "kpi_cycle_time", name: "Cycle Time", description: "Waktu siklus produksi per batch", dimension: "production", ownerExecutive: "COO", unit: "hours", higherIsBetter: false, calculation: "TotalProductionTime / BatchCount", dataSource: "production", refreshInterval: "weekly", tags: ["production", "speed"] },
  { id: "kpi_capacity_utilization", name: "Capacity Utilization", description: "Utilisasi kapasitas produksi", dimension: "production", ownerExecutive: "COO", unit: "%", higherIsBetter: true, calculation: "(ActualOutput / MaxCapacity) * 100", dataSource: "production", refreshInterval: "weekly", tags: ["production", "capacity"] },

  // Warehouse
  { id: "kpi_picking_accuracy", name: "Picking Accuracy", description: "Akurasi picking barang", dimension: "warehouse", ownerExecutive: "COO", unit: "%", higherIsBetter: true, calculation: "(1 - PickingErrors / TotalPicks) * 100", dataSource: "warehouse", refreshInterval: "daily", tags: ["warehouse", "quality"] },
  { id: "kpi_packing_speed", name: "Packing Speed", description: "Kecepatan packing per order", dimension: "warehouse", ownerExecutive: "COO", unit: "minutes", higherIsBetter: false, calculation: "TotalPackingTime / OrderCount", dataSource: "warehouse", refreshInterval: "weekly", tags: ["warehouse", "speed"] },
  { id: "kpi_warehouse_capacity", name: "Warehouse Capacity Used", description: "Persentase kapasitas gudang terpakai", dimension: "warehouse", ownerExecutive: "COO", unit: "%", higherIsBetter: false, calculation: "(UsedCapacity / TotalCapacity) * 100", dataSource: "warehouse", refreshInterval: "daily", tags: ["warehouse", "capacity"] },
  { id: "kpi_shipping_accuracy", name: "Shipping Accuracy", description: "Akurasi pengiriman", dimension: "warehouse", ownerExecutive: "COO", unit: "%", higherIsBetter: true, calculation: "(CorrectShipments / TotalShipments) * 100", dataSource: "warehouse", refreshInterval: "weekly", tags: ["warehouse", "quality"] },

  // CRM
  { id: "kpi_retention", name: "Customer Retention Rate", description: "Tingkat retensi pelanggan", dimension: "crm", ownerExecutive: "CMO", unit: "%", higherIsBetter: true, calculation: "(RepeatCustomers / TotalCustomers) * 100", dataSource: "crm", refreshInterval: "monthly", tags: ["crm", "retention"] },
  { id: "kpi_repeat_rate", name: "Repeat Purchase Rate", description: "Tingkat pembelian ulang", dimension: "crm", ownerExecutive: "CMO", unit: "%", higherIsBetter: true, calculation: "(CustomersWithRepeatOrders / TotalCustomers) * 100", dataSource: "crm", refreshInterval: "monthly", tags: ["crm", "loyalty"] },
  { id: "kpi_ltv", name: "Customer Lifetime Value", description: "Nilai seumur hidup pelanggan", dimension: "crm", ownerExecutive: "CMO", unit: "IDR", higherIsBetter: true, calculation: "AOV * PurchaseFrequency * AvgLifespan", dataSource: "crm", refreshInterval: "monthly", tags: ["crm", "value"] },
  { id: "kpi_churn_rate", name: "Churn Rate", description: "Tingkat kehilangan pelanggan", dimension: "crm", ownerExecutive: "CMO", unit: "%", higherIsBetter: false, calculation: "(LostCustomers / StartCustomers) * 100", dataSource: "crm", refreshInterval: "monthly", tags: ["crm", "churn"] },
  { id: "kpi_nps", name: "Net Promoter Score", description: "Skor loyalitas pelanggan", dimension: "crm", ownerExecutive: "CMO", unit: "score", higherIsBetter: true, calculation: "Promoters% - Detractors%", dataSource: "survey", refreshInterval: "monthly", tags: ["crm", "satisfaction"] },

  // Platform
  { id: "kpi_uptime", name: "System Uptime", description: "Persentase waktu sistem aktif", dimension: "platform", ownerExecutive: "CTO", unit: "%", higherIsBetter: true, calculation: "(UptimeHours / TotalHours) * 100", dataSource: "monitoring", refreshInterval: "daily", tags: ["platform", "reliability"] },
  { id: "kpi_error_rate", name: "Error Rate", description: "Tingkat error sistem", dimension: "platform", ownerExecutive: "CTO", unit: "%", higherIsBetter: false, calculation: "(ErrorCount / RequestCount) * 100", dataSource: "monitoring", refreshInterval: "daily", tags: ["platform", "quality"] },
  { id: "kpi_api_latency", name: "API Latency", description: "Rata-rata latency API", dimension: "platform", ownerExecutive: "CTO", unit: "ms", higherIsBetter: false, calculation: "AVG(response_time)", dataSource: "monitoring", refreshInterval: "daily", tags: ["platform", "performance"] },
  { id: "kpi_active_users", name: "Active Users", description: "Jumlah pengguna aktif", dimension: "platform", ownerExecutive: "CTO", unit: "count", higherIsBetter: true, calculation: "COUNT(active_sessions)", dataSource: "monitoring", refreshInterval: "daily", tags: ["platform", "usage"] },

  // Expansion
  { id: "kpi_branch_count", name: "Branch Count", description: "Jumlah cabang aktif", dimension: "expansion", ownerExecutive: "CEO", unit: "count", higherIsBetter: true, calculation: "COUNT(active_branches)", dataSource: "branches", refreshInterval: "monthly", tags: ["expansion", "growth"] },
  { id: "kpi_branch_profitability", name: "Branch Profitability", description: "Rata-rata profitabilitas per cabang", dimension: "expansion", ownerExecutive: "CEO", unit: "IDR", higherIsBetter: true, calculation: "SUM(BranchProfit) / BranchCount", dataSource: "finance", refreshInterval: "monthly", tags: ["expansion", "profitability"] },

  // Purchasing
  { id: "kpi_supplier_on_time", name: "Supplier On-Time Rate", description: "Tingkat ketepatan waktu supplier", dimension: "purchasing", ownerExecutive: "COO", unit: "%", higherIsBetter: true, calculation: "(OnTimeDeliveries / TotalDeliveries) * 100", dataSource: "purchasing", refreshInterval: "monthly", tags: ["purchasing", "supplier"] },
  { id: "kpi_po_cycle_time", name: "PO Cycle Time", description: "Rata-rata waktu siklus pembelian", dimension: "purchasing", ownerExecutive: "COO", unit: "days", higherIsBetter: false, calculation: "AVG(OrderToReceiptDays)", dataSource: "purchasing", refreshInterval: "monthly", tags: ["purchasing", "efficiency"] },
];

export function getAllDefinitions(): KPIDefinition[] { return [...KPI_DEFINITIONS]; }
export function getDefinition(id: string): KPIDefinition | undefined { return KPI_DEFINITIONS.find(d => d.id === id); }
export function getDefinitionsByDimension(dimension: Dimension): KPIDefinition[] { return KPI_DEFINITIONS.filter(d => d.dimension === dimension); }
export function getDefinitionsByExecutive(executive: string): KPIDefinition[] { return KPI_DEFINITIONS.filter(d => d.ownerExecutive === executive); }
export function getDefinitionCount(): number { return KPI_DEFINITIONS.length; }
