import type { BusinessCapability } from "../types";

export const FINANCE_CAPABILITY: BusinessCapability = {
  id: "cap_finance",
  name: "Finance Management",
  description: "Mengelola keuangan perusahaan termasuk pencatatan transaksi, kas, akuntansi, dan pelaporan",
  domain: "finance",
  version: "1.0.0",
  ownerExecutive: "CFO",
  supportedActions: [
    {
      name: "Record Expense",
      purpose: "Mencatat pengeluaran bisnis untuk operasional",
      whenUsed: "Pembelian ATK, pembayaran utilitas, biaya operasional harian",
      requiredContext: ["amount", "category", "description", "paidBy", "branchId", "paymentMethod"],
      approvalLevel: "manager",
      riskLevel: "low",
      eventsGenerated: ["finance.expense.recorded", "cash.outflow"],
      executionHandler: "FinanceRecordExpenseHandler",
      kpisAffected: ["operational_cost", "expense_ratio", "cash_flow"],
      businessConstraints: ["Biaya > 5jt perlu approval director", "Kategori biaya harus valid"],
      rollbackStrategy: "Reverse expense entry",
      examples: ["Bayar listrik cabang Rp 2.500.000", "Belanja ATK kantor Rp 500.000"],
    },
    {
      name: "Record Revenue",
      purpose: "Mencatat pendapatan non-penjualan seperti bunga, investasi, atau jasa",
      whenUsed: "Pendapatan di luar penjualan reguler",
      requiredContext: ["amount", "category", "description", "receivedBy", "branchId"],
      approvalLevel: "manager",
      riskLevel: "low",
      eventsGenerated: ["finance.revenue.recorded", "cash.inflow"],
      executionHandler: "FinanceRecordRevenueHandler",
      kpisAffected: ["total_revenue", "non_sales_revenue", "cash_flow"],
      businessConstraints: ["Revenue harus diverifikasi dengan dokumen pendukung"],
      rollbackStrategy: "Reverse revenue entry",
      examples: ["Pendapatan bunga bank Rp 150.000", "Jasa konsultasi Rp 2.000.000"],
    },
    {
      name: "Reconcile Account",
      purpose: "Merekon siliasi akun bank atau kas",
      whenUsed: "Akhir bulan, perbedaan catatan internal vs bank statement",
      requiredContext: ["accountId", "periodStart", "periodEnd", "statementData"],
      approvalLevel: "director",
      riskLevel: "high",
      eventsGenerated: ["finance.reconciliation", "reconciliation.completed", "reconciliation.discrepancy"],
      executionHandler: "FinanceReconcileHandler",
      kpisAffected: ["reconciliation_accuracy", "reconciliation_timeliness"],
      businessConstraints: ["Rekonsiliasi harus selesai dalam 7 hari setelah tutup bulan"],
      rollbackStrategy: "Restore pre-reconciliation state",
      examples: ["Rekonsiliasi Bank Mandiri cabang periode Januari", "Rekonsiliasi kas kecil"],
    },
    {
      name: "Approve Budget",
      purpose: "Menyetujui anggaran untuk departemen atau proyek",
      whenUsed: "Awal periode, pengajuan anggaran baru, atau revisi anggaran",
      requiredContext: ["budgetId", "approvedBy", "notes"],
      approvalLevel: "ceo",
      riskLevel: "high",
      eventsGenerated: ["finance.budget.approved", "budget.updated"],
      executionHandler: "FinanceApproveBudgetHandler",
      kpisAffected: ["budget_adherence", "budget_approval_time"],
      businessConstraints: ["Anggaran > 100jt perlu approval founder", "Semua anggaran harus sesuai RKAP"],
      rollbackStrategy: "Revert budget to previous approved version",
      examples: ["Approve anggaran marketing Q1 Rp 50jt", "Setujui budget operasional cabang baru"],
    },
    {
      name: "Generate Financial Report",
      purpose: "Membuat laporan keuangan (P&L, Balance Sheet, Cash Flow)",
      whenUsed: "Tutup buku, permintaan investor, atau kebutuhan manajemen",
      requiredContext: ["periodStart", "periodEnd", "reportType", "branchId"],
      approvalLevel: "none",
      riskLevel: "low",
      eventsGenerated: ["finance.report.generated", "report.completed"],
      executionHandler: "FinanceGenerateReportHandler",
      kpisAffected: ["reporting_timeliness", "report_accuracy"],
      businessConstraints: ["Data harus balance sebelum laporan digenerate"],
      rollbackStrategy: "None — read-only operation",
      examples: ["Laporan P&L bulan Desember", "Neraca keuangan tahun 2024"],
    },
    {
      name: "Manage Cash Flow",
      purpose: "Memantau dan mengelola arus kas harian",
      whenUsed: "Setiap hari untuk memastikan likuiditas terjaga",
      requiredContext: ["branchId", "date", "projection"],
      approvalLevel: "manager",
      riskLevel: "high",
      eventsGenerated: ["finance.cashflow.updated", "cashflow.warning", "cashflow.critical"],
      executionHandler: "FinanceManageCashFlowHandler",
      kpisAffected: ["cash_flow", "liquidity_ratio", "days_cash_on_hand"],
      businessConstraints: ["Cash flow harus dipantau setiap hari oleh CFO"],
      rollbackStrategy: "Restore previous cash flow projection",
      examples: ["Cek arus kas harian", "Proyeksi cash flow 7 hari ke depan"],
    },
    {
      name: "Close Books",
      purpose: "Menutup pembukuan akhir periode (harian/bulanan/tahunan)",
      whenUsed: "Akhir hari untuk tutup kas, akhir bulan, atau akhir tahun fiskal",
      requiredContext: ["periodType", "periodEnd", "branchId", "closedBy"],
      approvalLevel: "director",
      riskLevel: "critical",
      eventsGenerated: ["finance.books.closed", "books.closed", "period.closed"],
      executionHandler: "FinanceCloseBooksHandler",
      kpisAffected: ["closing_timeliness", "closing_accuracy"],
      businessConstraints: ["Semua transaksi harus sudah tercatat", "Tidak bisa dibuka kembali tanpa approval CFO"],
      rollbackStrategy: "Reopen period with CFO approval",
      examples: ["Tutup buku harian 31 Jan 2024", "Closing bulanan Januari 2024"],
    },
  ],
  requiredApprovals: ["manager", "director", "ceo"],
  requiredRoles: ["finance_staff", "accountant", "finance_manager", "cfo"],
  requiredContext: ["branchId", "userId", "periodStart", "periodEnd", "accountId"],
  requiredCapabilities: ["cap_sales", "cap_purchasing", "cap_inventory"],
  generatedEvents: [
    "finance.expense.recorded", "finance.revenue.recorded", "finance.reconciliation",
    "finance.budget.approved", "finance.report.generated", "finance.cashflow.updated",
    "finance.books.closed",
  ],
  affectedKPIs: [
    "cash_flow", "operational_cost", "expense_ratio", "total_revenue",
    "budget_adherence", "liquidity_ratio", "reporting_timeliness",
  ],
  executionHandler: "FinanceExecutionHandler",
  estimatedRisk: "high",
  estimatedComplexity: "complex",
  dependencies: ["cap_sales", "cap_purchasing", "cap_inventory"],
  postConditions: ["Jurnal tercatat di general ledger", "Saldo akun terupdate", "Audit trail tercatat"],
  rollbackStrategy: "Reverse journal entry via accounting ledger",
  executionType: "immediate",
  status: "active",
  tags: ["finance", "accounting", "budget", "cashflow", "reporting"],
  examples: ["Pencatatan biaya operasional", "Laporan keuangan bulanan", "Rekonsiliasi bank"],
};
