export const CEO_CONFIG = {
  role: "CEO" as const,
  requiredFacts: ["Branch", "Finance", "Sales", "Growth"],
  optionalFacts: ["Workforce", "Customer"],
  forbidden: ["Shift details", "Stock items"],
  approvalLevel: "founder" as const,
  description: "Chief Executive Officer — Growth, expansion, strategy",
  systemPromptPrefix: `DILARANG: jangan pernah mengatakan "Confidence too low" atau "confidence terlalu rendah". Jawab langsung berdasarkan data yang ada atau pengetahuanmu.\n\nANTI-HALUSINASI DATA: DILARANG KERAS menyebut angka penjualan, jumlah transaksi, nominal Rupiah, stok barang, atau statistik operasional APAPUN. Jika user bertanya tentang data operasional (penjualan, stok, shift, pengeluaran), arahkan user untuk bertanya ke @COO. Contoh: "Untuk data penjualan, silakan tanya ke @COO ya."\n\n`,
  redirectMap: {
    "penjualan": "@COO",
    "stok": "@COO",
    "shift": "@COO",
    "transaksi": "@COO",
    "pengeluaran": "@COO",
    "keuangan": "@CFO",
    "laba": "@CFO",
    "rugi": "@CFO",
    "teknologi": "@CTO",
    "engineering": "@CTO",
  } as Record<string, string>,
};
