import type { BusinessCapability } from "../types";

export const INVENTORY_CAPABILITY: BusinessCapability = {
  id: "cap_inventory",
  name: "Inventory Management",
  description: "Mengelola seluruh siklus hidup persediaan barang termasuk penerimaan, penyimpanan, penyesuaian, dan audit stok",
  domain: "inventory",
  version: "1.0.0",
  ownerExecutive: "COO",
  supportedActions: [
    {
      name: "Restock",
      purpose: "Menambah stok barang dari pemasok atau produksi internal",
      whenUsed: "Stok menipis, mendekati reorder point, atau permintaan meningkat",
      requiredContext: ["productId", "quantity", "branchId", "supplierId"],
      approvalLevel: "manager",
      riskLevel: "low",
      eventsGenerated: ["inventory.restock", "stock.increased", "inventory.cost.updated"],
      executionHandler: "InventoryRestockHandler",
      kpisAffected: ["stock_level", "reorder_rate", "inventory_turnover"],
      businessConstraints: ["Tidak boleh melebihi kapasitas gudang", "Minimum quantity harus >= 1"],
      rollbackStrategy: "Reverse movement + restore previous stock level",
      examples: ["Restock 100 unit Coca-Cola 500ml untuk Branch 1", "Menambah stok gula pasir 50kg dari supplier S01"],
    },
    {
      name: "Transfer Stock",
      purpose: "Memindahkan stok antar cabang atau gudang",
      whenUsed: "Stok berlebih di satu lokasi, kekurangan di lokasi lain",
      requiredContext: ["productId", "quantity", "fromBranchId", "toBranchId"],
      approvalLevel: "manager",
      riskLevel: "medium",
      eventsGenerated: ["inventory.transfer", "stock.decreased", "stock.increased"],
      executionHandler: "InventoryTransferHandler",
      kpisAffected: ["stock_level", "transfer_efficiency", "logistics_cost"],
      businessConstraints: ["Stok sumber harus mencukupi", "Tidak boleh transfer ke cabang yang sama"],
      rollbackStrategy: "Reverse transfer both branches",
      examples: ["Transfer 20 dus mie instan dari Gudang A ke Gudang B", "Pindahkan 50kg daging beku dari Branch 1 ke Branch 2"],
    },
    {
      name: "Adjust Stock",
      purpose: "Mengoreksi stok akibat kesalahan pencatatan, rusak, atau hilang",
      whenUsed: "Selisih stok fisik vs sistem, barang rusak, expired, atau hilang",
      requiredContext: ["productId", "quantity", "branchId", "reason"],
      approvalLevel: "manager",
      riskLevel: "high",
      eventsGenerated: ["inventory.adjust", "stock.adjusted", "inventory.loss"],
      executionHandler: "InventoryAdjustHandler",
      kpisAffected: ["stock_accuracy", "shrinkage_rate", "write_off_value"],
      businessConstraints: ["Adjustment quantity negatif harus disertai alasan", "Adjustment > 5% stok perlu approval director"],
      rollbackStrategy: "Restore previous stock and log correction",
      examples: ["Koreksi stok 5 unit karena barang rusak", "Adjust selisih opname +3 unit untuk produk A001"],
    },
    {
      name: "Audit Stock",
      purpose: "Melakukan audit stok menyeluruh atau sampling",
      whenUsed: "Periodik (bulanan/kvartal), indikasi masalah, atau pergantian manajemen",
      requiredContext: ["branchId", "auditScope", "auditorId"],
      approvalLevel: "director",
      riskLevel: "medium",
      eventsGenerated: ["inventory.audit", "audit.started", "audit.completed", "audit.discrepancy"],
      executionHandler: "InventoryAuditHandler",
      kpisAffected: ["stock_accuracy", "audit_compliance", "discrepancy_rate"],
      businessConstraints: ["Audit harus melibatkan minimal 2 petugas", "Audit mendadak perlu izin COO"],
      rollbackStrategy: "Restore pre-audit state",
      examples: ["Audit stok akhir bulan Gudang Pusat", "Sampling audit 10% produk kategori FMCG"],
    },
    {
      name: "Stock Count",
      purpose: "Menghitung stok fisik untuk verifikasi akurasi",
      whenUsed: "Siklus opname periodik, sebelum tutup buku, atau setelah restock besar",
      requiredContext: ["branchId", "productIds", "counterId"],
      approvalLevel: "manager",
      riskLevel: "low",
      eventsGenerated: ["inventory.count", "count.started", "count.completed", "count.discrepancy"],
      executionHandler: "InventoryStockCountHandler",
      kpisAffected: ["stock_accuracy", "count_efficiency", "discrepancy_rate"],
      businessConstraints: ["Produk yang sedang dalam transaksi tidak boleh dihitung"],
      rollbackStrategy: "Restore pre-count state",
      examples: ["Opname stok harian untuk kategori minuman", "Count stok mingguan produk frozen food"],
    },
    {
      name: "Reserve Stock",
      purpose: "Mereservasi stok untuk pesanan pelanggan atau produksi",
      whenUsed: "Pelanggan melakukan pre-order, produksi membutuhkan alokasi bahan baku",
      requiredContext: ["productId", "quantity", "branchId", "referenceId", "reservationType"],
      approvalLevel: "none",
      riskLevel: "low",
      eventsGenerated: ["inventory.reserve", "stock.reserved"],
      executionHandler: "InventoryReserveHandler",
      kpisAffected: ["reservation_rate", "fulfillment_rate"],
      businessConstraints: ["Reservasi otomatis expired dalam 24 jam", "Stok tersedia harus mencukupi"],
      rollbackStrategy: "Release reservation and restore available stock",
      examples: ["Reservasi 10 unit untuk PO-001", "Alokasi 50kg tepung untuk produksi shift malam"],
    },
    {
      name: "Release Reservation",
      purpose: "Membatalkan reservasi stok yang sudah tidak diperlukan",
      whenUsed: "Pesanan dibatalkan, expired, atau kebutuhan produksi berubah",
      requiredContext: ["reservationId", "reason"],
      approvalLevel: "none",
      riskLevel: "low",
      eventsGenerated: ["inventory.reserve.release", "stock.released"],
      executionHandler: "InventoryReleaseReservationHandler",
      kpisAffected: ["reservation_cancellation_rate"],
      businessConstraints: ["Reservasi yang sudah dipakai tidak bisa direlease"],
      rollbackStrategy: "Re-reserve stock",
      examples: ["Release reservasi PO-001 karena pesanan dibatalkan", "Release reservasi expired otomatis"],
    },
    {
      name: "Receive Goods",
      purpose: "Menerima barang dari pemasok dan menambah stok",
      whenUsed: "Barang dari pemasok tiba di gudang",
      requiredContext: ["purchaseOrderId", "productId", "quantity", "branchId", "receivedById"],
      approvalLevel: "none",
      riskLevel: "low",
      eventsGenerated: ["goods.received", "stock.increased", "purchase.completed"],
      executionHandler: "InventoryReceiveGoodsHandler",
      kpisAffected: ["receiving_efficiency", "supplier_accuracy"],
      businessConstraints: ["Quantity diterima tidak boleh melebihi PO", "Barang harus diperiksa kualitasnya"],
      rollbackStrategy: "Reverse goods receipt and update PO status",
      examples: ["Terima 200 unit dari PO-2024-001", "Receiving 50 dus dari supplier S01 sesuai delivery note"],
    },
    {
      name: "Dispose Goods",
      purpose: "Membuang barang rusak, expired, atau tidak layak jual",
      whenUsed: "Barang expired, rusak parah, recall, atau tidak layak konsumsi",
      requiredContext: ["productId", "quantity", "branchId", "reason", "disposalMethod"],
      approvalLevel: "manager",
      riskLevel: "medium",
      eventsGenerated: ["goods.disposed", "stock.decreased", "inventory.loss"],
      executionHandler: "InventoryDisposeHandler",
      kpisAffected: ["shrinkage_rate", "waste_percentage", "write_off_value"],
      businessConstraints: ["Disposal massal > 10 item perlu approval COO", "Metode disposal harus ramah lingkungan"],
      rollbackStrategy: "Cannot rollback disposal — log only",
      examples: ["Buang 5kg daging expired", "Dispose 20 unit produk recall kategori A"],
    },
    {
      name: "Inventory Valuation",
      purpose: "Menghitung nilai persediaan menggunakan metode FIFO, LIFO, atau Average",
      whenUsed: "Tutup buku bulanan, audit tahunan, atau kebutuhan laporan keuangan",
      requiredContext: ["branchId", "valuationMethod", "periodStart", "periodEnd"],
      approvalLevel: "director",
      riskLevel: "high",
      eventsGenerated: ["inventory.valuation", "valuation.completed", "valuation.discrepancy"],
      executionHandler: "InventoryValuationHandler",
      kpisAffected: ["inventory_value", "cogs", "gross_margin"],
      businessConstraints: ["Metode valuation harus konsisten sesuai kebijakan akuntansi"],
      rollbackStrategy: "Restore previous valuation snapshot",
      examples: ["Valuasi stok akhir bulan menggunakan FIFO", "Hitung nilai persediaan metode Average untuk audit"],
    },
  ],
  requiredApprovals: ["manager", "director"],
  requiredRoles: ["warehouse_staff", "inventory_manager", "branch_manager"],
  requiredContext: ["branchId", "userId", "businessDate"],
  requiredCapabilities: ["cap_purchasing"],
  generatedEvents: [
    "inventory.restock", "inventory.transfer", "inventory.adjust", "inventory.audit",
    "inventory.count", "inventory.reserve", "inventory.reserve.release",
    "goods.received", "goods.disposed", "inventory.valuation",
  ],
  affectedKPIs: [
    "stock_level", "inventory_turnover", "stock_accuracy", "shrinkage_rate",
    "reorder_rate", "write_off_value", "inventory_value", "cogs",
  ],
  executionHandler: "InventoryExecutionHandler",
  estimatedRisk: "medium",
  estimatedComplexity: "moderate",
  dependencies: ["cap_purchasing"],
  postConditions: ["Stock terupdate sesuai action", "Event tercatat di EventStore", "Audit trail tercatat"],
  rollbackStrategy: "Reverse inventory movement via stock ledger",
  executionType: "immediate",
  status: "active",
  tags: ["inventory", "stock", "warehouse", "logistics", "supply-chain"],
  examples: ["Manajemen stok harian untuk retail", "Opname stok akhir periode", "Transfer stok antar cabang"],
};
