import type { BusinessCapability } from "../types";

export const CRM_CAPABILITY: BusinessCapability = {
  id: "cap_crm",
  name: "Customer Relationship Management",
  description: "Mengelola hubungan dengan pelanggan termasuk data, loyalitas, segmentasi, dan komunikasi",
  domain: "crm",
  version: "1.0.0",
  ownerExecutive: "CMO",
  supportedActions: [
    {
      name: "Register Customer",
      purpose: "Mendaftarkan pelanggan baru ke dalam sistem",
      whenUsed: "Pelanggan baru melakukan pembelian atau mendaftar membership",
      requiredContext: ["name", "phone", "branchId", "customerType"],
      approvalLevel: "none",
      riskLevel: "low",
      eventsGenerated: ["crm.customer.registered", "customer.created"],
      executionHandler: "CRMRegisterCustomerHandler",
      kpisAffected: ["customer_acquisition", "member_growth"],
      businessConstraints: ["Nomor telepon harus unik", "Data pelanggan wajib lengkap"],
      rollbackStrategy: "Deactivate customer account",
      examples: ["Daftarkan member baru atas nama Budi", "Register customer korporat PT ABC"],
    },
    {
      name: "Update Loyalty Points",
      purpose: "Menambahkan atau menyesuaikan poin loyalitas pelanggan",
      whenUsed: "Setelah transaksi, bonus promosi, atau koreksi poin",
      requiredContext: ["customerId", "points", "reason", "branchId"],
      approvalLevel: "none",
      riskLevel: "low",
      eventsGenerated: ["crm.loyalty.updated", "loyalty.points.changed", "customer.rewards.earned"],
      executionHandler: "CRMLoyaltyHandler",
      kpisAffected: ["loyalty_redemption_rate", "member_engagement", "repeat_purchase_rate"],
      businessConstraints: ["Poin tidak bisa ditukar dengan uang tunai", "Poin expired dalam 1 tahun"],
      rollbackStrategy: "Reverse loyalty points adjustment",
      examples: ["Update poin 500 untuk transaksi Rp 500.000", "Bonus poin ulang tahun 1000 poin"],
    },
    {
      name: "Segment Customers",
      purpose: "Mengelompokkan pelanggan berdasarkan karakteristik atau perilaku",
      whenUsed: "Kampanye marketing, analisis bisnis, atau personalisasi layanan",
      requiredContext: ["segmentType", "criteria", "branchId"],
      approvalLevel: "none",
      riskLevel: "low",
      eventsGenerated: ["crm.segment.created", "customer.segment.updated"],
      executionHandler: "CRMSegmentHandler",
      kpisAffected: ["segment_accuracy", "campaign_effectiveness"],
      businessConstraints: ["Segmentasi harus berdasarkan data yang valid"],
      rollbackStrategy: "Revert to previous segmentation",
      examples: ["Segmentasi pelanggan berdasarkan frekuensi belanja", "Kelompokkan member gold dan platinum"],
    },
    {
      name: "Send Communication",
      purpose: "Mengirim komunikasi ke pelanggan via email, SMS, atau notifikasi",
      whenUsed: "Promosi, pengumuman, reminder, atau follow-up",
      requiredContext: ["customerIds", "channel", "message", "campaignId"],
      approvalLevel: "manager",
      riskLevel: "medium",
      eventsGenerated: ["crm.communication.sent", "campaign.communication.sent"],
      executionHandler: "CRMCommunicationHandler",
      kpisAffected: ["customer_engagement", "campaign_open_rate", "campaign_click_rate"],
      businessConstraints: ["Tidak boleh spam (maks 2x/minggu)", "Wajib ada opsi unsubscribe"],
      rollbackStrategy: "Cannot rollback sent communication",
      examples: ["Kirim promo akhir pekan ke semua member", "SMS reminder poin akan expired"],
    },
    {
      name: "Manage Feedback",
      purpose: "Mengelola feedback, keluhan, dan rating dari pelanggan",
      whenUsed: "Setelah transaksi, survei kepuasan, atau pelanggan memberikan masukan",
      requiredContext: ["customerId", "feedbackType", "rating", "comment", "branchId"],
      approvalLevel: "none",
      riskLevel: "low",
      eventsGenerated: ["crm.feedback.recorded", "customer.feedback", "complaint.raised"],
      executionHandler: "CRMFeedbackHandler",
      kpisAffected: ["customer_satisfaction", "nps_score", "complaint_resolution_time"],
      businessConstraints: ["Keluhan harus direspon dalam 24 jam"],
      rollbackStrategy: "Archive feedback entry",
      examples: ["Catat rating 4/5 dari pelanggan", "Follow-up keluhan tentang pelayanan kasir"],
    },
    {
      name: "Process Referral",
      purpose: "Mencatat dan memberikan reward untuk program referral pelanggan",
      whenUsed: "Pelanggan mereferensikan teman atau keluarga yang melakukan pendaftaran",
      requiredContext: ["referrerId", "referredId", "rewardType"],
      approvalLevel: "none",
      riskLevel: "low",
      eventsGenerated: ["crm.referral.processed", "referral.rewarded"],
      executionHandler: "CRMReferralHandler",
      kpisAffected: ["referral_rate", "customer_acquisition_cost"],
      businessConstraints: ["Referred customer harus melakukan transaksi pertama"],
      rollbackStrategy: "Reverse referral reward",
      examples: ["Proses referral A undang B daftar", "Reward 100 poin untuk referral berhasil"],
    },
  ],
  requiredApprovals: ["manager"],
  requiredRoles: ["crm_staff", "marketing_staff", "branch_manager"],
  requiredContext: ["branchId", "userId", "customerId"],
  requiredCapabilities: [],
  generatedEvents: [
    "crm.customer.registered", "crm.loyalty.updated", "crm.segment.created",
    "crm.communication.sent", "crm.feedback.recorded", "crm.referral.processed",
  ],
  affectedKPIs: [
    "customer_acquisition", "member_growth", "customer_satisfaction", "nps_score",
    "loyalty_redemption_rate", "repeat_purchase_rate", "customer_engagement",
  ],
  executionHandler: "CRMExecutionHandler",
  estimatedRisk: "low",
  estimatedComplexity: "simple",
  dependencies: [],
  postConditions: ["Data pelanggan terupdate", "Poin loyalitas tercatat"],
  rollbackStrategy: "Reverse customer data changes with audit trail",
  executionType: "immediate",
  status: "active",
  tags: ["crm", "customer", "loyalty", "communication", "feedback"],
  examples: ["Pendaftaran member baru", "Program loyalitas dan poin", "Segmentasi pelanggan untuk promosi"],
};
