import { Router } from "express";
import authRouter from "./auth";  // ← tambah import
import healthRouter from "./health";
import usersRouter from "./users";
import categoriesRouter from "./categories";
import productsRouter from "./products";
import productVariantsRouter from "./productVariants";
import ordersRouter from "./orders";
import dashboardRouter from "./dashboard";
import branchesRouter from "./branches";
import ingredientsRouter from "./ingredients";
import semiFinishedRouter from "./semiFinished";
import recipesRouter from "./recipes";
import inventoryRouter from "./inventory";
import warehouseRouter from "../inventory/routes/warehouse";
import stockCardRouter from "../inventory/routes/stockCard";
import inventoryMovementRouter from "../inventory/routes/inventory";
import hrDepartmentRouter from "../hr/routes/departments";
import hrEmployeeRouter from "../hr/routes/employees";
import hrPositionRouter from "../hr/routes/positions";
import hrExtraRouter from "../hr/routes/hrRoutes";
import hrAttendanceRouter from "../hr/routes/attendance";
import purchasingSupplierRouter from "../purchasing/routes/suppliers";
import purchasingPoRouter from "../purchasing/routes/purchaseOrders";
import purchasingReceiptRouter from "../purchasing/routes/goodsReceipts";
import purchasingInvoiceRouter from "../purchasing/routes/invoices";
import hrLeaveRouter from "../hr/routes/leaves";
import expensesRouter from "./expenses";
import shiftAuditsRouter from "./shiftAudits";
import storageRouter from "./storage";
import aiRouter from "./ai";
import migrateRouter from "./migrate";
import financeRouter from "./finance";
import itemsRouter from "./items";
import uomsRouter from "./uoms";
import binsRouter from "./bins";
import agingRouter from "../inventory/routes/aging";
import analyticsRouter from "../inventory/routes/analytics";

const router = Router();

router.use("/", authRouter);  // ← tambah (harus sebelum route lain)
router.use("/", healthRouter);
router.use("/", usersRouter);
router.use("/", categoriesRouter);
router.use("/", productsRouter);
router.use("/", productVariantsRouter);
router.use("/", ordersRouter);
router.use("/", dashboardRouter);
router.use("/", branchesRouter);
router.use("/", ingredientsRouter);
router.use("/", semiFinishedRouter);
router.use("/", recipesRouter);
router.use("/", inventoryRouter);
router.use("/", warehouseRouter);
router.use("/", stockCardRouter);
router.use("/", inventoryMovementRouter);
router.use("/", hrDepartmentRouter);
router.use("/", hrEmployeeRouter);
router.use("/", hrPositionRouter);
router.use("/", hrExtraRouter);
router.use("/", hrAttendanceRouter);
router.use("/", hrLeaveRouter);
router.use("/", purchasingSupplierRouter);
router.use("/", purchasingPoRouter);
router.use("/", purchasingReceiptRouter);
router.use("/", purchasingInvoiceRouter);
router.use("/", expensesRouter);
router.use("/", shiftAuditsRouter);
router.use("/", storageRouter);
router.use("/", aiRouter);
router.use("/", migrateRouter);
router.use("/", financeRouter);
router.use("/", itemsRouter);
router.use("/", uomsRouter);
router.use("/", binsRouter);
router.use("/", agingRouter);
router.use("/", analyticsRouter);

export default router;