import type { BusinessCapability } from "../types";

export const HR_CAPABILITY: BusinessCapability = {
  id: "cap_hr",
  name: "Human Resources Management",
  description: "Mengelola sumber daya manusia termasuk rekrutmen, payroll, absensi, dan pengembangan karyawan",
  domain: "hr",
  version: "1.0.0",
  ownerExecutive: "CHRO",
  supportedActions: [
    {
      name: "Recruit Employee",
      purpose: "Memproses rekrutmen karyawan baru dari posting hingga onboarding",
      whenUsed: "Ada kebutuhan tenaga kerja baru, replacement, atau ekspansi",
      requiredContext: ["positionTitle", "department", "branchId", "requirements", "headcount"],
      approvalLevel: "manager",
      riskLevel: "medium",
      eventsGenerated: ["hr.recruitment.started", "recruitment.completed", "employee.onboarded"],
      executionHandler: "HRRecruitHandler",
      kpisAffected: ["time_to_hire", "cost_per_hire", "hiring_quality"],
      businessConstraints: ["Headcount harus sesuai budget", "Proses rekrutmen maksimal 60 hari"],
      rollbackStrategy: "Cancel recruitment process",
      examples: ["Rekrut 5 kasir baru untuk Branch 3", "Cari replacement untuk manager yang resign"],
    },
    {
      name: "Manage Payroll",
      purpose: "Memproses penggajian karyawan termasuk gaji, bonus, dan potongan",
      whenUsed: "Periode penggajian (bulanan/mingguan) atau pembayaran bonus",
      requiredContext: ["periodStart", "periodEnd", "branchId", "payrollType"],
      approvalLevel: "director",
      riskLevel: "high",
      eventsGenerated: ["hr.payroll.processed", "payroll.completed", "salary.disbursed"],
      executionHandler: "HRPayrollHandler",
      kpisAffected: ["payroll_accuracy", "payroll_timeliness", "labor_cost"],
      businessConstraints: ["Payroll harus selesai H-1 tanggal gajian", "Potongan pajak dan BPJS wajib"],
      rollbackStrategy: "Reverse payroll entries and recalculate",
      examples: ["Proses payroll bulan Januari 2024", "Hitung bonus tahunan untuk semua karyawan"],
    },
    {
      name: "Record Attendance",
      purpose: "Mencatat kehadiran, izin, cuti, atau lembur karyawan",
      whenUsed: "Setiap hari untuk absensi, atau saat pengajuan cuti/izin/lembur",
      requiredContext: ["employeeId", "date", "attendanceType", "checkIn", "checkOut"],
      approvalLevel: "none",
      riskLevel: "low",
      eventsGenerated: ["hr.attendance.recorded", "attendance.updated", "leave.applied"],
      executionHandler: "HRAttendanceHandler",
      kpisAffected: ["attendance_rate", "absenteeism", "overtime_hours"],
      businessConstraints: ["Cuti harus diajukan H-1", "Lembur maksimal 4 jam/hari sesuai aturan"],
      rollbackStrategy: "Revert attendance entry",
      examples: ["Catat absensi harian shift pagi", "Approval cuti tahunan 3 hari"],
    },
    {
      name: "Evaluate Performance",
      purpose: "Melakukan evaluasi kinerja karyawan secara periodik",
      whenUsed: "Review periodik (bulanan/kvartal/tahunan), promosi, atau penentuan bonus",
      requiredContext: ["employeeId", "periodStart", "periodEnd", "evaluatorId"],
      approvalLevel: "manager",
      riskLevel: "medium",
      eventsGenerated: ["hr.performance.evaluated", "evaluation.completed"],
      executionHandler: "HRPerformanceHandler",
      kpisAffected: ["performance_score", "employee_productivity"],
      businessConstraints: ["Evaluasi harus berdasarkan KPI terukur", "Feedback dari atasan langsung wajib"],
      rollbackStrategy: "Revert to previous evaluation",
      examples: ["Review kinerja Q1 untuk staff marketing", "Evaluasi tahunan seluruh karyawan"],
    },
    {
      name: "Manage Training",
      purpose: "Merencanakan dan mencatat pelatihan dan pengembangan karyawan",
      whenUsed: "Identifikasi gap skill, onboarding karyawan baru, atau requirement sertifikasi",
      requiredContext: ["employeeId", "trainingType", "trainingProvider", "schedule"],
      approvalLevel: "manager",
      riskLevel: "low",
      eventsGenerated: ["hr.training.scheduled", "training.completed", "employee.skill.updated"],
      executionHandler: "HRTrainingHandler",
      kpisAffected: ["training_hours", "skill_improvement", "certification_rate"],
      businessConstraints: ["Setiap karyawan minimal 20 jam pelatihan/tahun"],
      rollbackStrategy: "Cancel training enrollment",
      examples: ["Jadwalkan training barista untuk staff baru", "Sertifikasi HACCP untuk tim produksi"],
    },
    {
      name: "Terminate Employee",
      purpose: "Memproses penghentian hubungan kerja",
      whenUsed: "Resignasi, pensiun, PHK, atau pelanggaran berat",
      requiredContext: ["employeeId", "terminationType", "effectiveDate", "reason", "approvedBy"],
      approvalLevel: "director",
      riskLevel: "critical",
      eventsGenerated: ["hr.termination.processed", "employee.offboarded"],
      executionHandler: "HRTerminateHandler",
      kpisAffected: ["turnover_rate", "retention_rate"],
      businessConstraints: ["PHK harus sesuai UU Ketenagakerjaan", "Pesangon wajib dibayarkan sesuai aturan"],
      rollbackStrategy: "Cannot rollback — legal implications",
      examples: ["Proses resignasi karyawan A001", "PHK karena pelanggaran berat"],
    },
  ],
  requiredApprovals: ["manager", "director"],
  requiredRoles: ["hr_staff", "hr_manager", "branch_manager", "chro"],
  requiredContext: ["branchId", "userId", "employeeId", "departmentId"],
  requiredCapabilities: ["cap_finance"],
  generatedEvents: [
    "hr.recruitment.started", "hr.payroll.processed", "hr.attendance.recorded",
    "hr.performance.evaluated", "hr.training.scheduled", "hr.termination.processed",
  ],
  affectedKPIs: [
    "time_to_hire", "cost_per_hire", "payroll_accuracy", "attendance_rate",
    "turnover_rate", "performance_score", "training_hours",
  ],
  executionHandler: "HRExecutionHandler",
  estimatedRisk: "high",
  estimatedComplexity: "complex",
  dependencies: ["cap_finance"],
  postConditions: ["Data karyawan terupdate", "Payroll tercatat", "Attendance tercatat"],
  rollbackStrategy: "Revert HR transaction with audit trail",
  executionType: "immediate",
  status: "active",
  tags: ["hr", "people", "payroll", "attendance", "recruitment", "training"],
  examples: ["Rekrutmen staff baru", "Proses payroll bulanan", "Manajemen cuti dan absensi"],
};
