import type { BusinessCapability } from "../types";

export const MARKETING_CAPABILITY: BusinessCapability = {
  id: "cap_marketing",
  name: "Marketing Management",
  description: "Mengelola strategi dan eksekusi marketing termasuk kampanye, promosi, iklan, dan branding",
  domain: "marketing",
  version: "1.0.0",
  ownerExecutive: "CMO",
  supportedActions: [
    {
      name: "Create Campaign",
      purpose: "Membuat kampanye marketing untuk promosi produk atau brand awareness",
      whenUsed: "Peluncuran produk baru, event musiman, atau target penjualan tertentu",
      requiredContext: ["campaignName", "objective", "targetAudience", "budget", "timeline", "channels"],
      approvalLevel: "manager",
      riskLevel: "medium",
      eventsGenerated: ["marketing.campaign.created", "campaign.started"],
      executionHandler: "MarketingCreateCampaignHandler",
      kpisAffected: ["campaign_reach", "campaign_conversion", "roi"],
      businessConstraints: ["Budget campaign harus sesuai alokasi", "Pesan campaign harus sesuai brand guidelines"],
      rollbackStrategy: "Cancel campaign and release budget",
      examples: ["Kampanye promo akhir tahun dengan diskon 20%", "Launch campaign produk minuman baru"],
    },
    {
      name: "Manage Promotion",
      purpose: "Mengelola program promosi seperti diskon, buy 1 get 1, cashback",
      whenUsed: "Meningkatkan penjualan, clear stok, atau merayakan momen tertentu",
      requiredContext: ["promotionType", "products", "discountValue", "periodStart", "periodEnd", "branchId"],
      approvalLevel: "manager",
      riskLevel: "medium",
      eventsGenerated: ["marketing.promotion.created", "promotion.started", "promotion.ended"],
      executionHandler: "MarketingPromotionHandler",
      kpisAffected: ["promotion_redemption", "sales_impact", "margin_impact"],
      businessConstraints: ["Diskon maksimal 50% tanpa approval CEO", "Promosi tidak boleh merugikan secara struktural"],
      rollbackStrategy: "End promotion early and restore prices",
      examples: ["Promo buy 1 get 1 untuk semua minuman", "Diskon 25% untuk produk frozen food"],
    },
    {
      name: "Manage Social Media",
      purpose: "Mengelola konten dan interaksi di media sosial",
      whenUsed: "Posting konten, merespon komentar, atau menjadwalkan posting",
      requiredContext: ["platform", "contentType", "content", "schedule", "branchId"],
      approvalLevel: "none",
      riskLevel: "low",
      eventsGenerated: ["marketing.social.posted", "social.media.updated"],
      executionHandler: "MarketingSocialMediaHandler",
      kpisAffected: ["social_engagement", "follower_growth", "reach"],
      businessConstraints: ["Konten harus sesuai brand voice", "Respons komentar maksimal 2 jam"],
      rollbackStrategy: "Delete or unpublish post",
      examples: ["Posting promo akhir pekan di Instagram", "Jadwalkan konten TikTok untuk besok"],
    },
    {
      name: "Track Competitor",
      purpose: "Memantau aktivitas dan strategi kompetitor",
      whenUsed: "Analisis pasar, pricing review, atau perencanaan strategi",
      requiredContext: ["competitorName", "trackingType", "period"],
      approvalLevel: "none",
      riskLevel: "low",
      eventsGenerated: ["marketing.competitor.tracked", "competitor.analysis.completed"],
      executionHandler: "MarketingCompetitorHandler",
      kpisAffected: ["market_share", "competitive_index"],
      businessConstraints: ["Data kompetitor harus dari sumber yang valid"],
      rollbackStrategy: "None — read-only operation",
      examples: ["Pantau harga kompetitor untuk kategori minuman", "Analisis campaign kompetitor bulan ini"],
    },
    {
      name: "Analyze Market",
      purpose: "Menganalisis tren pasar, perilaku konsumen, dan peluang bisnis",
      whenUsed: "Perencanaan strategis, identifikasi peluang baru, atau evaluasi performa",
      requiredContext: ["analysisType", "periodStart", "periodEnd", "marketSegment"],
      approvalLevel: "none",
      riskLevel: "low",
      eventsGenerated: ["marketing.analysis.completed", "market.insight.generated"],
      executionHandler: "MarketingAnalysisHandler",
      kpisAffected: ["market_share", "customer_insight_score"],
      businessConstraints: ["Analisis harus berdasarkan data terkini"],
      rollbackStrategy: "None — read-only operation",
      examples: ["Analisis tren penjualan Q1 2024", "Riset pasar untuk ekspensi ke kota baru"],
    },
    {
      name: "Manage Brand Assets",
      purpose: "Mengelola aset brand termasuk logo, guideline, dan materi marketing",
      whenUsed: "Rebranding, pembuatan materi baru, atau audit brand consistency",
      requiredContext: ["assetType", "description", "branchId"],
      approvalLevel: "manager",
      riskLevel: "low",
      eventsGenerated: ["marketing.brand.asset.updated", "brand.guideline.changed"],
      executionHandler: "MarketingBrandHandler",
      kpisAffected: ["brand_awareness", "brand_consistency"],
      businessConstraints: ["Semua materi harus sesuai brand guidelines"],
      rollbackStrategy: "Restore previous brand asset version",
      examples: ["Update logo untuk cabang baru", "Upload materi iklan untuk campaign"],
    },
  ],
  requiredApprovals: ["manager"],
  requiredRoles: ["marketing_staff", "marketing_manager", "social_media_specialist", "brand_manager"],
  requiredContext: ["branchId", "userId", "budgetId"],
  requiredCapabilities: ["cap_crm", "cap_finance", "cap_sales"],
  generatedEvents: [
    "marketing.campaign.created", "marketing.promotion.created", "marketing.social.posted",
    "marketing.competitor.tracked", "marketing.analysis.completed", "marketing.brand.asset.updated",
  ],
  affectedKPIs: [
    "campaign_reach", "campaign_conversion", "roi", "social_engagement",
    "follower_growth", "market_share", "brand_awareness",
  ],
  executionHandler: "MarketingExecutionHandler",
  estimatedRisk: "medium",
  estimatedComplexity: "moderate",
  dependencies: ["cap_crm", "cap_finance", "cap_sales"],
  postConditions: ["Kampanye tercatat", "Promosi aktif sesuai jadwal", "Data marketing teranalisa"],
  rollbackStrategy: "Cancel campaign/promotion and restore baseline",
  executionType: "immediate",
  status: "active",
  tags: ["marketing", "campaign", "promotion", "social-media", "brand", "analytics"],
  examples: ["Kampanye promo bulanan", "Manajemen media sosial", "Analisis pasar dan kompetitor"],
};
