import type { BusinessCapability } from "../types";

export const PURCHASING_CAPABILITY: BusinessCapability = {
  id: "cap_purchasing",
  name: "Purchasing & Procurement",
  description: "Mengelola proses pembelian barang dari pemasok termasuk PO, penerimaan, dan pembayaran",
  domain: "purchasing",
  version: "1.0.0",
  ownerExecutive: "COO",
  supportedActions: [
    {
      name: "Create Purchase Order",
      purpose: "Membuat purchase order untuk pemesanan barang ke pemasok",
      whenUsed: "Stok menipis, reorder point tercapai, atau permintaan produksi",
      requiredContext: ["supplierId", "items", "branchId", "expectedDate", "budget"],
      approvalLevel: "manager",
      riskLevel: "medium",
      eventsGenerated: ["purchase.order.created", "po.created", "procurement.started"],
      executionHandler: "PurchasingCreatePOHandler",
      kpisAffected: ["procurement_lead_time", "po_accuracy"],
      businessConstraints: ["PO harus sesuai budget yang dialokasikan", "Minimal pemesanan sesuai supplier"],
      rollbackStrategy: "Cancel purchase order",
      examples: ["PO 100 unit Coca-Cola ke supplier S01", "Pesan bahan baku produksi untuk 1 bulan"],
    },
    {
      name: "Approve Purchase Order",
      purpose: "Menyetujui purchase order sebelum dikirim ke pemasok",
      whenUsed: "Setelah PO dibuat, perlu verifikasi budget dan persetujuan",
      requiredContext: ["purchaseOrderId", "approvedBy", "notes"],
      approvalLevel: "manager",
      riskLevel: "medium",
      eventsGenerated: ["purchase.order.approved", "po.approved"],
      executionHandler: "PurchasingApprovePOHandler",
      kpisAffected: ["approval_time", "po_approval_rate"],
      businessConstraints: ["PO > 10jt perlu approval director", "PO > 50jt perlu approval CEO"],
      rollbackStrategy: "Reject and return to pending",
      examples: ["Approve PO-2024-001 untuk restock", "Setujui pembelian mesin baru Rp 45jt"],
    },
    {
      name: "Receive Purchase",
      purpose: "Menerima barang yang dipesan sesuai PO",
      whenUsed: "Barang dari supplier tiba, diverifikasi quantity dan kualitas",
      requiredContext: ["purchaseOrderId", "receivedItems", "receivedById", "grnNumber"],
      approvalLevel: "none",
      riskLevel: "low",
      eventsGenerated: ["purchase.received", "goods.received", "po.completed"],
      executionHandler: "PurchasingReceiveHandler",
      kpisAffected: ["supplier_accuracy", "receiving_efficiency"],
      businessConstraints: ["Penerimaan tidak boleh melebihi quantity PO", "QC wajib untuk bahan baku"],
      rollbackStrategy: "Reverse goods receipt and update PO status",
      examples: ["Terima 100 unit sesuai PO-001", "Receiving parsial 50 dari 100 unit PO-002"],
    },
    {
      name: "Evaluate Supplier",
      purpose: "Menilai kinerja pemasok berdasarkan kualitas, ketepatan, dan harga",
      whenUsed: "Evaluasi periodik atau setelah transaksi tertentu",
      requiredContext: ["supplierId", "evaluationPeriod", "criteria"],
      approvalLevel: "manager",
      riskLevel: "low",
      eventsGenerated: ["purchase.supplier.evaluated", "supplier.rating.updated"],
      executionHandler: "PurchasingEvaluateSupplierHandler",
      kpisAffected: ["supplier_score", "on_time_delivery", "supplier_quality"],
      businessConstraints: ["Evaluasi dilakukan setiap kuartal untuk supplier aktif"],
      rollbackStrategy: "Revert to previous supplier rating",
      examples: ["Evaluasi supplier S01 untuk Q1 2024", "Nilai supplier baru setelah 3 bulan"],
    },
    {
      name: "Manage Supplier Contract",
      purpose: "Mengelola kontrak dengan pemasok termasuk harga, volume, dan ketentuan",
      whenUsed: "Kontrak baru, perpanjangan, renegosiasi, atau terminasi",
      requiredContext: ["supplierId", "contractType", "startDate", "endDate", "terms"],
      approvalLevel: "director",
      riskLevel: "high",
      eventsGenerated: ["purchase.contract.created", "contract.updated", "contract.expired"],
      executionHandler: "PurchasingContractHandler",
      kpisAffected: ["contract_compliance", "procurement_cost_savings"],
      businessConstraints: ["Kontrak > 1 tahun perlu legal review", "Harga kontrak mengikat selama periode"],
      rollbackStrategy: "Terminate contract with notice period",
      examples: ["Kontrak tahunan dengan supplier gula", "Perpanjangan kontrak supplier kemasan"],
    },
  ],
  requiredApprovals: ["manager", "director"],
  requiredRoles: ["procurement_staff", "procurement_manager", "warehouse_staff"],
  requiredContext: ["branchId", "userId", "supplierId", "budgetId"],
  requiredCapabilities: ["cap_inventory", "cap_finance"],
  generatedEvents: [
    "purchase.order.created", "purchase.order.approved", "purchase.received",
    "purchase.supplier.evaluated", "purchase.contract.created",
  ],
  affectedKPIs: [
    "procurement_lead_time", "supplier_score", "on_time_delivery",
    "procurement_cost", "po_accuracy",
  ],
  executionHandler: "PurchasingExecutionHandler",
  estimatedRisk: "medium",
  estimatedComplexity: "moderate",
  dependencies: ["cap_inventory", "cap_finance"],
  postConditions: ["PO tercatat", "Stok bertambah setelah receive", "Hutang tercatat di finance"],
  rollbackStrategy: "Cancel PO and reverse any received goods",
  executionType: "immediate",
  status: "active",
  tags: ["purchasing", "procurement", "supplier", "po", "contract"],
  examples: ["Pembelian stok rutin dari supplier", "Manajemen kontrak supplier", "Evaluasi supplier periodik"],
};
