import type { BusinessCapability } from "../types";

export const PLATFORM_CAPABILITY: BusinessCapability = {
  id: "cap_platform",
  name: "Platform & Technology",
  description: "Mengelola platform teknologi, sistem informasi, infrastruktur IT, dan inovasi digital",
  domain: "platform",
  version: "1.0.0",
  ownerExecutive: "CTO",
  supportedActions: [
    {
      name: "Manage System Access",
      purpose: "Mengelola akses pengguna ke sistem termasuk role, permission, dan autentikasi",
      whenUsed: "Karyawan baru, perubahan peran, atau audit keamanan",
      requiredContext: ["userId", "role", "permissions", "branchId"],
      approvalLevel: "manager",
      riskLevel: "high",
      eventsGenerated: ["platform.access.granted", "access.revoked", "user.role.updated"],
      executionHandler: "PlatformAccessHandler",
      kpisAffected: ["system_security", "access_management_efficiency"],
      businessConstraints: ["Privilege minimal sesuai prinsip least privilege", "Akses sensitive但 perlu approval director"],
      rollbackStrategy: "Revoke access and restore previous permissions",
      examples: ["Buat akun untuk karyawan baru", "Setel permission kasir untuk Branch 3"],
    },
    {
      name: "Configure System",
      purpose: "Mengkonfigurasi pengaturan sistem termasuk parameter bisnis dan preferensi",
      whenUsed: "Setup cabang baru, perubahan kebijakan, atau update konfigurasi",
      requiredContext: ["configKey", "configValue", "scope", "branchId"],
      approvalLevel: "manager",
      riskLevel: "high",
      eventsGenerated: ["platform.config.updated", "system.configuration.changed"],
      executionHandler: "PlatformConfigureHandler",
      kpisAffected: ["system_stability", "configuration_accuracy"],
      businessConstraints: ["Konfigurasi kritis perlu backup sebelum diubah"],
      rollbackStrategy: "Restore previous configuration",
      examples: ["Set pajak default 11% untuk semua cabang", "Konfigurasi jam operasional cabang"],
    },
    {
      name: "Monitor System Health",
      purpose: "Memantau kesehatan sistem termasuk performa, error, dan availability",
      whenUsed: "Continuous monitoring, atau saat ada indikasi masalah",
      requiredContext: ["monitoringType", "period", "branchId"],
      approvalLevel: "none",
      riskLevel: "low",
      eventsGenerated: ["platform.health.reported", "system.alert", "system.healthy"],
      executionHandler: "PlatformMonitorHandler",
      kpisAffected: ["system_uptime", "system_performance", "error_rate"],
      businessConstraints: ["Monitoring real-time untuk sistem production"],
      rollbackStrategy: "None — read-only operation",
      examples: ["Cek kesehatan server POS", "Monitor performa database"],
    },
    {
      name: "Manage Data Backup",
      purpose: "Mengelola backup data dan pemulihan bencana",
      whenUsed: "Backup rutin, sebelum update besar, atau setelah insiden",
      requiredContext: ["backupType", "scope", "schedule", "retention"],
      approvalLevel: "director",
      riskLevel: "critical",
      eventsGenerated: ["platform.backup.created", "backup.completed", "backup.restored"],
      executionHandler: "PlatformBackupHandler",
      kpisAffected: ["data_integrity", "recovery_time", "backup_success_rate"],
      businessConstraints: ["Backup harus di lokasi berbeda (offsite)", "Test restore minimal 1x/bulan"],
      rollbackStrategy: "Restore from previous backup",
      examples: ["Backup full database malam hari", "Test restore backup untuk audit"],
    },
    {
      name: "Deploy Update",
      purpose: "Melakukan deployment update sistem atau fitur baru",
      whenUsed: "Rilis fitur baru, patch keamanan, atau perbaikan bug",
      requiredContext: ["updateType", "version", "description", "schedule", "approval"],
      approvalLevel: "director",
      riskLevel: "critical",
      eventsGenerated: ["platform.update.deployed", "system.updated", "deployment.completed"],
      executionHandler: "PlatformDeployHandler",
      kpisAffected: ["deployment_success_rate", "time_to_market", "system_stability"],
      businessConstraints: ["Deployment production harus di luar jam sibuk", "Rollback plan wajib disiapkan"],
      rollbackStrategy: "Rollback to previous version",
      examples: ["Deploy update POS v2.1.0", "Patch keamanan untuk modul payment"],
    },
    {
      name: "Manage Integration",
      purpose: "Mengelola integrasi dengan sistem pihak ketiga",
      whenUsed: "Integrasi dengan partner baru, update API, atau troubleshooting koneksi",
      requiredContext: ["integrationType", "partner", "apiEndpoint", "config"],
      approvalLevel: "manager",
      riskLevel: "high",
      eventsGenerated: ["platform.integration.updated", "integration.configured", "integration.failed"],
      executionHandler: "PlatformIntegrationHandler",
      kpisAffected: ["integration_success_rate", "api_availability"],
      businessConstraints: ["API key harus disimpan aman", "Integrasi harus diuji di staging dulu"],
      rollbackStrategy: "Disable integration and revert to previous state",
      examples: ["Integrasi dengan GoFood API", "Setup koneksi ke supplier portal"],
    },
  ],
  requiredApprovals: ["manager", "director"],
  requiredRoles: ["it_staff", "system_administrator", "developer", "it_manager", "cto"],
  requiredContext: ["branchId", "userId", "systemScope"],
  requiredCapabilities: [],
  generatedEvents: [
    "platform.access.granted", "platform.config.updated", "platform.health.reported",
    "platform.backup.created", "platform.update.deployed", "platform.integration.updated",
  ],
  affectedKPIs: [
    "system_uptime", "system_performance", "deployment_success_rate",
    "data_integrity", "system_security",
  ],
  executionHandler: "PlatformExecutionHandler",
  estimatedRisk: "high",
  estimatedComplexity: "complex",
  dependencies: [],
  postConditions: ["Sistem terkonfigurasi", "Akses terkelola", "Data terbackup"],
  rollbackStrategy: "System-wide rollback with version control",
  executionType: "immediate",
  status: "active",
  tags: ["platform", "technology", "it", "system", "infrastructure", "integration"],
  examples: ["Manajemen akses pengguna", "Deploy update sistem", "Backup dan recovery data"],
};
