import type { BusinessCapability } from "../types";

export const SALES_CAPABILITY: BusinessCapability = {
  id: "cap_sales",
  name: "Sales Management",
  description: "Mengelola transaksi penjualan, retur, diskon, dan laporan penjualan di seluruh cabang",
  domain: "sales",
  version: "1.0.0",
  ownerExecutive: "CEO",
  supportedActions: [
    {
      name: "Create Transaction",
      purpose: "Mencatat transaksi penjualan baru",
      whenUsed: "Pelanggan melakukan pembelian di kasir atau melalui sistem POS",
      requiredContext: ["customerId", "items", "totalAmount", "branchId", "paymentMethod"],
      approvalLevel: "none",
      riskLevel: "low",
      eventsGenerated: ["sales.transaction.created", "sales.completed", "stock.decreased"],
      executionHandler: "SalesCreateTransactionHandler",
      kpisAffected: ["daily_sales", "transaction_count", "average_transaction_value"],
      businessConstraints: ["Minimal 1 item per transaksi", "Total amount harus positif"],
      rollbackStrategy: "Void transaction + restore stock",
      examples: ["Penjualan 3 item kepada customer walk-in", "Transaksi member dengan poin rewards"],
    },
    {
      name: "Void Transaction",
      purpose: "Membatalkan transaksi penjualan yang sudah tercatat",
      whenUsed: "Kesalahan input, pembatalan oleh pelanggan, atau duplikasi transaksi",
      requiredContext: ["transactionId", "reason", "approvedBy"],
      approvalLevel: "manager",
      riskLevel: "medium",
      eventsGenerated: ["sales.transaction.voided", "stock.increased", "sales.reversed"],
      executionHandler: "SalesVoidTransactionHandler",
      kpisAffected: ["void_rate", "transaction_accuracy"],
      businessConstraints: ["Void hanya bisa dilakukan di hari yang sama", "Void transaksi > 500k perlu approval manager"],
      rollbackStrategy: "Restore transaction and adjust stock",
      examples: ["Void transaksi karena salah scan item", "Batalkan transaksi duplikat"],
    },
    {
      name: "Process Return",
      purpose: "Memproses retur barang dari pelanggan",
      whenUsed: "Pelanggan mengembalikan barang karena cacat, salah, atau tidak sesuai",
      requiredContext: ["transactionId", "items", "returnReason", "branchId"],
      approvalLevel: "manager",
      riskLevel: "medium",
      eventsGenerated: ["sales.return.processed", "stock.increased", "sales.refunded"],
      executionHandler: "SalesProcessReturnHandler",
      kpisAffected: ["return_rate", "customer_satisfaction", "refund_amount"],
      businessConstraints: ["Retur dalam 7 hari dari pembelian", "Barang harus dalam kondisi lengkap"],
      rollbackStrategy: "Reverse return and restore sale",
      examples: ["Retur 1 item karena cacat produksi", "Pengembalian barang tidak sesuai pesanan"],
    },
    {
      name: "Apply Discount",
      purpose: "Memberikan diskon pada transaksi atau item tertentu",
      whenUsed: "Promosi, member rewards, atau kebijakan harga khusus",
      requiredContext: ["transactionId", "discountType", "discountValue", "reason", "approvedBy"],
      approvalLevel: "manager",
      riskLevel: "medium",
      eventsGenerated: ["sales.discount.applied", "sales.amount.adjusted"],
      executionHandler: "SalesApplyDiscountHandler",
      kpisAffected: ["discount_rate", "average_discount", "sales_margin"],
      businessConstraints: ["Diskon maksimal 50% tanpa approval director", "Diskon member tetap sesuai tier"],
      rollbackStrategy: "Remove discount and restore original amount",
      examples: ["Diskon 10% untuk member gold", "Promo buy 1 get 1 kategori minuman"],
    },
    {
      name: "Generate Sales Report",
      purpose: "Membuat laporan penjualan harian, mingguan, bulanan",
      whenUsed: "End of day, review periodik, atau permintaan manajemen",
      requiredContext: ["branchId", "periodStart", "periodEnd", "reportType"],
      approvalLevel: "none",
      riskLevel: "low",
      eventsGenerated: ["sales.report.generated"],
      executionHandler: "SalesGenerateReportHandler",
      kpisAffected: ["reporting_timeliness"],
      businessConstraints: ["Data penjualan harus sudah di-reconcile"],
      rollbackStrategy: "None — read-only operation",
      examples: ["Laporan penjualan harian Branch 1", "Rekap penjualan bulanan untuk CFO"],
    },
  ],
  requiredApprovals: ["manager"],
  requiredRoles: ["cashier", "sales_supervisor", "branch_manager"],
  requiredContext: ["branchId", "userId", "businessDate", "customerId"],
  requiredCapabilities: ["cap_inventory", "cap_crm"],
  generatedEvents: [
    "sales.transaction.created", "sales.transaction.voided", "sales.return.processed",
    "sales.discount.applied", "sales.report.generated",
  ],
  affectedKPIs: [
    "daily_sales", "transaction_count", "average_transaction_value",
    "return_rate", "discount_rate", "customer_satisfaction",
  ],
  executionHandler: "SalesExecutionHandler",
  estimatedRisk: "low",
  estimatedComplexity: "simple",
  dependencies: ["cap_inventory", "cap_crm"],
  postConditions: ["Transaksi tercatat", "Stok terupdate", "Point pelanggan terakumulasi"],
  rollbackStrategy: "Void transaction and restore inventory",
  executionType: "immediate",
  status: "active",
  tags: ["sales", "pos", "transaction", "retail", "customer"],
  examples: ["Transaksi penjualan di kasir", "Retur barang", "Laporan penjualan harian"],
};
