import type { BusinessScenario } from "../types";

export const inventoryScenarios: BusinessScenario[] = [
  {
    id: "inv-001", name: "Stock Low Warning", domain: "inventory",
    description: "Stok produk menipis di bawah minimum threshold",
    trigger: { type: "event", eventType: "stock.low", data: { productId: 101, productName: "Tepung Terigu", currentStock: 5, minStock: 20, unit: "kg", branchId: 1 }, branchId: 1 },
    expectedExecutive: "COO", expectedCapabilities: ["cap_inventory", "cap_purchasing"],
    expectedActions: ["Restock", "CreatePurchaseOrder"], expectedEvents: ["inventory.restock", "purchasing.order_created"],
    priority: "high", tags: ["inventory", "supply-chain", "automatic"],
  },
  {
    id: "inv-002", name: "Stock Out Emergency", domain: "inventory",
    description: "Stok benar-benar habis, produksi terhenti",
    trigger: { type: "event", eventType: "stock.out", data: { productId: 102, productName: "Gula Pasir", currentStock: 0, minStock: 50, unit: "kg", lastOrderDate: "2026-07-20", branchId: 1 }, branchId: 1 },
    expectedExecutive: "COO", expectedCapabilities: ["cap_inventory", "cap_purchasing", "cap_production"],
    expectedActions: ["EmergencyRestock", "ExpediteOrder"], expectedEvents: ["inventory.stock_out", "purchasing.expedite", "production.delayed"],
    priority: "critical", tags: ["inventory", "emergency", "production-impact"],
  },
  {
    id: "inv-003", name: "Overstock Detected", domain: "inventory",
    description: "Stok berlebih mengikat modal kerja",
    trigger: { type: "event", eventType: "inventory.overstock", data: { productId: 103, productName: "Minyak Goreng", currentStock: 500, maxStock: 200, unit: "liter", value: 12500000, branchId: 1 }, branchId: 1 },
    expectedExecutive: "COO", expectedCapabilities: ["cap_inventory", "cap_sales"],
    expectedActions: ["PromotionPlan", "TransferStock"], expectedEvents: ["inventory.overstock_resolved", "sales.promotion_created"],
    priority: "high", tags: ["inventory", "finance", "working-capital"],
  },
  {
    id: "inv-004", name: "Dead Stock Identification", domain: "inventory",
    description: "Produk tidak bergerak selama 90 hari",
    trigger: { type: "event", eventType: "inventory.dead_stock", data: { productId: 104, productName: "Bumbu Instan Rasa A", currentStock: 200, lastSold: "2026-04-15", value: 4000000, branchId: 1 }, branchId: 1 },
    expectedExecutive: "COO", expectedCapabilities: ["cap_inventory", "cap_sales"],
    expectedActions: ["DiscountPlan", "WriteOff"], expectedEvents: ["inventory.dead_stock_flagged", "sales.discount_approved"],
    priority: "normal", tags: ["inventory", "slow-moving", "profitability"],
  },
  {
    id: "inv-005", name: "Supplier Delay Impact", domain: "inventory",
    description: "Supplier terlambat mengirim, stok terancam kosong",
    trigger: { type: "event", eventType: "supplier.delay", data: { supplierId: 501, supplierName: "PT Sumber Makmur", productId: 105, productName: "Telur Ayam", expectedDate: "2026-07-25", newDate: "2026-07-30", delayDays: 5, branchId: 1 }, branchId: 1 },
    expectedExecutive: "COO", expectedCapabilities: ["cap_inventory", "cap_purchasing"],
    expectedActions: ["FindAlternativeSupplier", "AdjustProduction"], expectedEvents: ["supplier.delay_mitigated", "purchasing.alternative_found"],
    priority: "high", tags: ["inventory", "supplier", "risk"],
  },
  {
    id: "inv-006", name: "Inventory Shrinkage", domain: "inventory",
    description: "Selisih stok fisik dengan sistem",
    trigger: { type: "event", eventType: "inventory.shrinkage", data: { productId: 106, productName: "Kopi Bubuk", systemStock: 100, physicalStock: 87, difference: 13, unit: "kg", estimatedLoss: 650000, branchId: 1 }, branchId: 1 },
    expectedExecutive: "COO", expectedCapabilities: ["cap_inventory"],
    expectedActions: ["InvestigateShrinkage", "AdjustStock"], expectedEvents: ["inventory.shrinkage_investigated"],
    priority: "normal", tags: ["inventory", "audit", "loss-prevention"],
  },
  {
    id: "inv-007", name: "Expired Stock Alert", domain: "inventory",
    description: "Produk mendekati tanggal kedaluwarsa",
    trigger: { type: "event", eventType: "inventory.expiring", data: { productId: 107, productName: "Susu UHT", currentStock: 300, expiryDate: "2026-08-15", daysLeft: 7, value: 4500000, branchId: 1 }, branchId: 1 },
    expectedExecutive: "COO", expectedCapabilities: ["cap_inventory", "cap_sales"],
    expectedActions: ["DiscountForQuickSale", "Donate"], expectedEvents: ["inventory.expiry_mitigated"],
    priority: "high", tags: ["inventory", "expiry", "loss-prevention"],
  },
  {
    id: "inv-008", name: "Stock Transfer Needed", domain: "inventory",
    description: "Satu cabang kelebihan, cabang lain kekurangan",
    trigger: { type: "event", eventType: "inventory.transfer_needed", data: { productId: 108, productName: "Air Mineral", fromBranchId: 1, toBranchId: 2, quantity: 200, reason: "Branch 2 stock low, Branch 1 overstock", branchId: 1 }, branchId: 1 },
    expectedExecutive: "COO", expectedCapabilities: ["cap_inventory", "cap_warehouse"],
    expectedActions: ["InitiateTransfer", "UpdateStock"], expectedEvents: ["inventory.transfer_initiated"],
    priority: "normal", tags: ["inventory", "logistics", "multi-branch"],
  },
  {
    id: "inv-009", name: "Reorder Point Triggered", domain: "inventory",
    description: "Sistem otomatis memicu reorder point",
    trigger: { type: "event", eventType: "inventory.reorder_point", data: { productId: 109, productName: "Mie Instan", reorderPoint: 100, currentStock: 105, avgDailyUsage: 30, leadTime: 3, branchId: 1 }, branchId: 1 },
    expectedExecutive: "COO", expectedCapabilities: ["cap_inventory", "cap_purchasing"],
    expectedActions: ["AutoReorder"], expectedEvents: ["inventory.reorder_placed"],
    priority: "normal", tags: ["inventory", "automation", "replenishment"],
  },
  {
    id: "inv-010", name: "Batch Expiry Tracking", domain: "inventory",
    description: "Batch tertentu serentak kedaluwarsa",
    trigger: { type: "event", eventType: "inventory.batch_expiry", data: { batchId: "B2026-07", productId: 110, productName: "Roti Tawar", quantity: 500, expiryDate: "2026-07-30", daysLeft: 4, branchId: 1 }, branchId: 1 },
    expectedExecutive: "COO", expectedCapabilities: ["cap_inventory"],
    expectedActions: ["BatchDiscount", "BulkDonation"], expectedEvents: ["inventory.batch_expiry_handled"],
    priority: "high", tags: ["inventory", "batch", "expiry"],
  },
];
