import type { BusinessCapability } from "../types";

export const EXPANSION_CAPABILITY: BusinessCapability = {
  id: "cap_expansion",
  name: "Business Expansion",
  description: "Mengelola ekspansi bisnis termasuk pembukaan cabang baru, perluasan pasar, dan pengembangan bisnis",
  domain: "expansion",
  version: "1.0.0",
  ownerExecutive: "CEO",
  supportedActions: [
    {
      name: "Open New Branch",
      purpose: "Membuka cabang baru di lokasi strategis",
      whenUsed: "Ekspansi bisnis ke lokasi baru, pertumbuhan pasar, atau peluang strategis",
      requiredContext: ["location", "initialBudget", "targetOpenDate", "branchType", "feasibilityStudy"],
      approvalLevel: "ceo",
      riskLevel: "critical",
      eventsGenerated: ["expansion.branch.created", "branch.opened", "expansion.started"],
      executionHandler: "ExpansionOpenBranchHandler",
      kpisAffected: ["branch_count", "expansion_speed", "new_branch_roi"],
      businessConstraints: ["Feasibility study wajib sebelum buka cabang", "Modal minimal sesuai kebijakan perusahaan"],
      rollbackStrategy: "Close branch and liquidate assets",
      examples: ["Buka cabang baru di Jakarta Selatan", "Ekspansi ke kota Bandung dengan format mini"],
    },
    {
      name: "Expand Product Line",
      purpose: "Menambah lini produk baru atau kategori baru",
      whenUsed: "Diversifikasi produk, permintaan pasar, atau inovasi bisnis",
      requiredContext: ["productCategory", "research", "initialInvestment", "targetMarket"],
      approvalLevel: "director",
      riskLevel: "high",
      eventsGenerated: ["expansion.product.line.created", "product.category.expanded"],
      executionHandler: "ExpandProductLineHandler",
      kpisAffected: ["product_diversity", "new_product_revenue", "innovation_rate"],
      businessConstraints: ["Produk baru harus lolos uji pasar", "R&D wajib dilakukan sebelumnya"],
      rollbackStrategy: "Discontinue product line",
      examples: ["Tambah lini produk frozen food", "Ekspansi ke kategori minuman kesehatan"],
    },
    {
      name: "Enter New Market",
      purpose: "Memasuki pasar baru (kota, provinsi, atau segmen baru)",
      whenUsed: "Peluang pasar baru, permintaan tinggi, atau strategi pertumbuhan agresif",
      requiredContext: ["marketType", "targetRegion", "strategy", "budget", "timeline"],
      approvalLevel: "founder",
      riskLevel: "critical",
      eventsGenerated: ["expansion.market.entered", "market.expansion.completed"],
      executionHandler: "ExpansionMarketHandler",
      kpisAffected: ["market_share", "revenue_growth", "expansion_cost"],
      businessConstraints: ["Riset pasar wajib dilakukan", "Regulasi daerah harus dipenuhi"],
      rollbackStrategy: "Exit market and minimize losses",
      examples: ["Ekspansi ke pasar kota Surabaya", "Masuk ke segmen HORECA (Hotel, Restoran, Café)"],
    },
    {
      name: "Establish Partnership",
      purpose: "Menjalin kemitraan strategis dengan pihak ketiga",
      whenUsed: "Kolaborasi bisnis, integrasi supply chain, atau perluasan distribusi",
      requiredContext: ["partnerName", "partnershipType", "terms", "duration", "expectedValue"],
      approvalLevel: "director",
      riskLevel: "high",
      eventsGenerated: ["expansion.partnership.created", "partnership.established"],
      executionHandler: "ExpansionPartnershipHandler",
      kpisAffected: ["partnership_value", "distribution_coverage"],
      businessConstraints: ["Due diligence wajib dilakukan", "Kontrak harus direview legal"],
      rollbackStrategy: "Terminate partnership with notice period",
      examples: ["Kerjasama dengan GoFood untuk delivery", "Kemitraan dengan supplier bahan baku utama"],
    },
    {
      name: "Conduct Feasibility Study",
      purpose: "Melakukan studi kelayakan untuk ekspansi atau investasi",
      whenUsed: "Sebelum keputusan ekspansi, investasi besar, atau akuisisi",
      requiredContext: ["studyType", "location", "parameters", "budget"],
      approvalLevel: "manager",
      riskLevel: "low",
      eventsGenerated: ["expansion.feasibility.completed", "feasibility.study.done"],
      executionHandler: "ExpansionFeasibilityHandler",
      kpisAffected: ["feasibility_accuracy"],
      businessConstraints: ["Studi harus mencakup aspek finansial, operasional, dan pasar"],
      rollbackStrategy: "None — read-only operation",
      examples: ["Studi kelayakan buka cabang di Bekasi", "Feasibility study ekspansi lini produk baru"],
    },
    {
      name: "Plan Expansion Roadmap",
      purpose: "Membuat roadmap ekspansi jangka panjang",
      whenUsed: "Perencanaan tahunan, strategi pertumbuhan, atau setelah pendanaan",
      requiredContext: ["vision", "targetMarkets", "budget", "timeline", "milestones"],
      approvalLevel: "ceo",
      riskLevel: "high",
      eventsGenerated: ["expansion.roadmap.created", "expansion.roadmap.updated"],
      executionHandler: "ExpansionRoadmapHandler",
      kpisAffected: ["expansion_speed", "plan_accuracy"],
      businessConstraints: ["Roadmap harus realistis sesuai kemampuan finansial"],
      rollbackStrategy: "Revise roadmap",
      examples: ["Roadmap ekspansi 5 tahun ke depan", "Rencana buka 10 cabang baru di 2024"],
    },
  ],
  requiredApprovals: ["ceo", "founder"],
  requiredRoles: ["ceo", "cfo", "coo", "business_development", "legal"],
  requiredContext: ["budget", "location", "timeline", "feasibilityStudy"],
  requiredCapabilities: ["cap_warehouse", "cap_hr", "cap_inventory", "cap_finance", "cap_marketing", "cap_crm"],
  generatedEvents: [
    "expansion.branch.created", "expansion.product.line.created", "expansion.market.entered",
    "expansion.partnership.created", "expansion.feasibility.completed", "expansion.roadmap.created",
  ],
  affectedKPIs: [
    "branch_count", "expansion_speed", "new_branch_roi", "market_share",
    "revenue_growth", "expansion_cost", "product_diversity",
  ],
  executionHandler: "ExpansionExecutionHandler",
  estimatedRisk: "critical",
  estimatedComplexity: "very_complex",
  dependencies: ["cap_warehouse", "cap_hr", "cap_inventory", "cap_finance", "cap_marketing", "cap_crm"],
  postConditions: ["Cabang baru aktif", "SDM terpenuhi", "Stok awal tersedia", "Marketing siap"],
  rollbackStrategy: "Systematic reversal of expansion steps",
  executionType: "async",
  status: "active",
  tags: ["expansion", "growth", "branch", "market", "partnership", "feasibility"],
  examples: ["Pembukaan cabang baru", "Ekspansi ke kota baru", "Kemitraan strategis"],
};
