import {
  Home, Crown, LayoutDashboard, Sparkles, Settings, Target,
  ShoppingBag, TrendingUp, Package, Users, UserCog, ShoppingCart,
  Store, BarChart3, Brain, Rocket, CircleUserRound, Shield,
  Layers, Briefcase, LineChart, Wallet, Boxes, Factory,
  Megaphone, Globe2, FileBarChart, UserRoundPlus, HardHat,
} from "lucide-react";
import type { IconMap } from "./types";

export const iconMap: IconMap = {
  Home,
  Crown,
  LayoutDashboard,
  Sparkles,
  Settings,
  Target,
  ShoppingBag,
  TrendingUp,
  Package,
  Users,
  UserCog,
  ShoppingCart,
  Store,
  BarChart3,
  Brain,
  Rocket,
  CircleUserRound,
  Shield,
  Layers,
  Briefcase,
  LineChart,
  Wallet,
  Boxes,
  Factory,
  Megaphone,
  Globe2,
  FileBarChart,
  UserRoundPlus,
  HardHat,
};