import type { BusinessCapability } from "../types";

export const PRODUCTION_CAPABILITY: BusinessCapability = {
  id: "cap_production",
  name: "Production Management",
  description: "Mengelola proses produksi dari perencanaan hingga eksekusi termasuk bill of materials dan quality control",
  domain: "production",
  version: "1.0.0",
  ownerExecutive: "COO",
  supportedActions: [
    {
      name: "Create Production Order",
      purpose: "Membuat order produksi untuk memproduksi barang tertentu",
      whenUsed: "Stok produk jadi menipis, ada permintaan khusus, atau produksi terjadwal",
      requiredContext: ["productId", "quantity", "branchId", "scheduledDate", "priority"],
      approvalLevel: "manager",
      riskLevel: "medium",
      eventsGenerated: ["production.order.created", "production.scheduled"],
      executionHandler: "ProductionCreateOrderHandler",
      kpisAffected: ["production_output", "production_efficiency", "on_time_production"],
      businessConstraints: ["Bahan baku harus tersedia", "Kapasitas produksi harian terbatas"],
      rollbackStrategy: "Cancel production order and release BOM",
      examples: ["Produksi 1000 roti tawar untuk besok", "Order produksi 500 box nasi kotak"],
    },
    {
      name: "Start Production",
      purpose: "Memulai eksekusi produksi dan mengalokasikan bahan baku",
      whenUsed: "Sesuai jadwal produksi, bahan baku dan tenaga kerja siap",
      requiredContext: ["productionOrderId", "operatorId", "startTime"],
      approvalLevel: "none",
      riskLevel: "medium",
      eventsGenerated: ["production.started", "bom.reserved", "production.in_progress"],
      executionHandler: "ProductionStartHandler",
      kpisAffected: ["production_efficiency", "downtime_rate"],
      businessConstraints: ["Bahan baku harus sudah direservasi", "Mesin dan operator harus siap"],
      rollbackStrategy: "Cancel production and return BOM to inventory",
      examples: ["Mulai produksi roti shift pagi", "Start produksi catering untuk event"],
    },
    {
      name: "Complete Production",
      purpose: "Menyelesaikan produksi dan menambah stok produk jadi",
      whenUsed: "Produksi selesai, quality control lulus",
      requiredContext: ["productionOrderId", "completedQuantity", "wasteQuantity", "inspectorId"],
      approvalLevel: "none",
      riskLevel: "low",
      eventsGenerated: ["production.completed", "stock.increased", "production.cost.recorded"],
      executionHandler: "ProductionCompleteHandler",
      kpisAffected: ["production_output", "yield_rate", "waste_percentage"],
      businessConstraints: ["QC harus lulus sebelum produk masuk stok", "Produk cacat dipisahkan"],
      rollbackStrategy: "Reverse production output and restore BOM",
      examples: ["Selesaikan produksi 950 roti (50 waste)", "Complete order produksi 500 box"],
    },
    {
      name: "Manage BOM",
      purpose: "Mengelola Bill of Materials untuk setiap produk",
      whenUsed: "Produk baru, perubahan resep/formula, atau optimasi biaya",
      requiredContext: ["productId", "ingredients", "quantities", "cost"],
      approvalLevel: "manager",
      riskLevel: "medium",
      eventsGenerated: ["production.bom.updated", "bom.changed", "product.cost.updated"],
      executionHandler: "ProductionBOMHandler",
      kpisAffected: ["product_cost", "bom_accuracy"],
      businessConstraints: ["Setiap produk harus memiliki BOM yang valid"],
      rollbackStrategy: "Restore previous BOM version",
      examples: ["Update BOM roti tawar dengan resep baru", "Tambah ingredient baru ke BOM kue"],
    },
    {
      name: "Quality Control",
      purpose: "Melakukan pemeriksaan kualitas produk jadi atau bahan baku",
      whenUsed: "Setelah produksi, penerimaan bahan baku, atau audit kualitas periodik",
      requiredContext: ["productId", "batchId", "inspectorId", "checklist", "result"],
      approvalLevel: "none",
      riskLevel: "low",
      eventsGenerated: ["production.qc.passed", "production.qc.failed", "production.qc.flagged"],
      executionHandler: "ProductionQualityControlHandler",
      kpisAffected: ["quality_score", "defect_rate", "customer_complaint_rate"],
      businessConstraints: ["QC wajib untuk setiap batch produksi", "Sampel sesuai standar AQL"],
      rollbackStrategy: "Revert QC status for retesting",
      examples: ["QC batch produksi roti shift pagi", "Inspeksi bahan baku dari supplier baru"],
    },
  ],
  requiredApprovals: ["manager"],
  requiredRoles: ["production_operator", "production_supervisor", "quality_control", "production_manager"],
  requiredContext: ["branchId", "userId", "productionOrderId", "productId"],
  requiredCapabilities: ["cap_inventory", "cap_purchasing"],
  generatedEvents: [
    "production.order.created", "production.started", "production.completed",
    "production.bom.updated", "production.qc.passed", "production.qc.failed",
  ],
  affectedKPIs: [
    "production_output", "production_efficiency", "yield_rate", "defect_rate",
    "product_cost", "on_time_production",
  ],
  executionHandler: "ProductionExecutionHandler",
  estimatedRisk: "medium",
  estimatedComplexity: "moderate",
  dependencies: ["cap_inventory", "cap_purchasing"],
  postConditions: ["Produk jadi bertambah", "Bahan baku berkurang", "Biaya produksi tercatat"],
  rollbackStrategy: "Cancel production and reverse BOM consumption",
  executionType: "immediate",
  status: "active",
  tags: ["production", "manufacturing", "bom", "qc", "quality"],
  examples: ["Produksi roti harian", "Manajemen BOM untuk produk F&B", "Quality control batch produksi"],
};
