// ECP-030: Consultant Schema — output format specifications
// Frozen. All consultant outputs follow these schemas.
// Ensures consistent format for Founder consumption.

import type { Finding, ConsultantRecommendation, WeeklyReport, MonthlyReport } from "./consultant-types";

export function formatFinding(finding: Finding): string {
  return [
    `## Finding: ${finding.type}`,
    `${finding.description}`,
    `Severity: ${finding.severity} | Domain: ${finding.domain}`,
    `Evidence: ${finding.evidence.join(", ")}`,
  ].join("\n");
}

export function formatRecommendation(rec: ConsultantRecommendation): string {
  return [
    `## Recommendation`,
    `Action: ${rec.action}`,
    `Rationale: ${rec.rationale}`,
    `Confidence: ${rec.confidence}% | Priority: ${rec.priority}`,
    `Owner: ${rec.owner} | Effort: ${rec.estimatedEffort}`,
    `Impact: ${rec.expectedImpact}`,
    rec.proposedADR ? `Proposed ADR: ${rec.proposedADR}` : "",
  ].filter(Boolean).join("\n");
}

export function formatWeeklyReport(report: WeeklyReport): string {
  return [
    `# Weekly Organization Health — ${report.period}`,
    "",
    report.summary,
    "",
    `## Metrics`,
    `Knowledge Growth: +${report.knowledgeGrowth} cards`,
    `Mission Success: ${report.missionSuccess}%`,
    `Failure Trend: ${report.failureTrend}`,
    `Architecture Debt: ${report.architectureDebtCount} items`,
    `Policy Drift: ${report.policyDriftCount} items`,
    `Open Recommendations: ${report.openRecommendations}`,
    "",
    `## Top Findings`,
    ...report.topFindings.map(f => `- [${f.severity}] ${f.description}`),
    "",
    `## Next Priorities`,
    ...report.nextPriorities.map(p => `- ${p}`),
  ].join("\n");
}

export function formatMonthlyReport(report: MonthlyReport): string {
  return [
    `# Monthly Executive Summary — ${report.period}`,
    "",
    report.executiveSummary,
    "",
    `## Knowledge`,
    `Growth: +${report.knowledgeGrowth} | Total Cards: ${report.knowledgeCardCount}`,
    `Foundation Candidates: ${report.foundationCandidates}`,
    `Foundation Proposals: ${report.foundationProposals}`,
    "",
    `## Runtime Performance`,
    `Mission Success: ${report.runtimePerformance.missionSuccessRate}%`,
    `Avg Completion: ${Math.round(report.runtimePerformance.avgCompletionTimeMs / 1000)}s`,
    `Token Efficiency: ${report.runtimePerformance.tokenEfficiency}%`,
    "",
    `## Top Improvements`,
    ...report.topImprovements.map(i => `- ${i}`),
    "",
    `## Biggest Risks`,
    ...report.biggestRisks.map(r => `- ${r}`),
    "",
    `## Organization Health Score: ${report.organizationHealthScore}/100`,
  ].join("\n");
}

export function formatProposal(rec: ConsultantRecommendation): string {
  return [
    `# ADR Proposal (Auto-generated by Consultant Runtime)`,
    `Status: ${rec.status}`,
    "",
    `## Problem`,
    `Action: ${rec.action}`,
    `Rationale: ${rec.rationale}`,
    "",
    `## Analysis`,
    `Confidence: ${rec.confidence}%`,
    `Expected Impact: ${rec.expectedImpact}`,
    `Estimated Effort: ${rec.estimatedEffort}`,
    "",
    `## Recommendation`,
    `Owner: ${rec.owner}`,
    `Priority: ${rec.priority}`,
    "",
    `> This proposal was auto-generated by Consultant Runtime (CKO).`,
    `> It is a recommendation only. Final decision rests with Founder.`,
  ].join("\n");
}
